/**
 * Generates the per-table TRQL schema the dashboard assistant's getTableSchema
 * tool serves. The system prompt only names the tables; the agent fetches a
 * table's columns once via getTableSchema and reuses them — same pattern as
 * searchApi → getApiDetails. Source of truth is `app/v3/querySchemas.ts`.
 *
 * Run it whenever querySchemas.ts changes:
 *
 *   pnpm exec tsx apps/webapp/scripts/generate-ai-trql-schema.ts
 *
 * Lives in scripts/ (NOT app/trigger/) because the trigger CLI indexes and
 * imports everything under app/trigger at boot; querySchemas pulls in webapp-only
 * modules (React components, logger.server) that must not enter the worker bundle.
 * The generated output is a plain data module, safe to import from the worker.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ColumnSchema, TableSchema } from "@internal/tsql";
import { querySchemas } from "../app/v3/querySchemas";

const here =
  typeof __dirname !== "undefined" ? __dirname : dirname(fileURLToPath(import.meta.url));

const OUTPUT_PATH = resolve(here, "../app/lib/ai-assistant/trql-schema.generated.ts");

function allowedValues(col: ColumnSchema): string[] | undefined {
  if (col.valueMap) return Object.values(col.valueMap);
  if (col.allowedValues && col.allowedValues.length > 0) return col.allowedValues;
  return undefined;
}

function serializeColumn(col: ColumnSchema) {
  const out: Record<string, unknown> = { name: col.name, type: col.type };
  if (col.description) out.description = col.description;
  const values = allowedValues(col);
  if (values) out.allowedValues = values;
  return out;
}

function serializeTable(table: TableSchema) {
  return {
    name: table.name,
    description: table.description,
    timeColumn: table.timeConstraint,
    columns: Object.values(table.columns).map(serializeColumn),
  };
}

const tables = querySchemas.map(serializeTable);

const fileContents = `// GENERATED by scripts/generate-ai-trql-schema.ts — do not edit by hand.
// Regenerate after changing app/v3/querySchemas.ts:
//   pnpm exec tsx apps/webapp/scripts/generate-ai-trql-schema.ts

export interface TrqlColumn {
  name: string;
  type: string;
  description?: string;
  allowedValues?: string[];
}

export interface TrqlTable {
  name: string;
  description: string;
  timeColumn?: string;
  columns: TrqlColumn[];
}

export const trqlTables: TrqlTable[] = ${JSON.stringify(tables, null, 2)};
`;

writeFileSync(OUTPUT_PATH, fileContents, "utf8");

const columnCount = tables.reduce((n, t) => n + t.columns.length, 0);
console.log(`Wrote ${OUTPUT_PATH}\n  ${tables.length} tables, ${columnCount} columns`);
