packages:
  - "packages/*"
  - "internal-packages/*"
  - "apps/**"
  - "references/*"
  - "docs"
  - "!packages/cli-v3/e2e/**"

minimumReleaseAge: 4320
preferOffline: true

linkWorkspacePackages: false
publicHoistPattern:
  - "*prisma*"
preferWorkspacePackages: true
sideEffectsCache: false