export const checkoutSessionExample = {
  id: "test_session",
  name: "Mock Checkout Session",
  icon: "stripe",
  payload: {
    id: "cs_test_a1LFuyKHsmzBxr6SvxfFu184ISK2sNebnb60DloYuCenBcJtfGttTydm4n",
    object: "checkout.session",
    after_expiration: null,
    allow_promotion_codes: null,
    amount_subtotal: 3000,
    amount_total: 3000,
    automatic_tax: {
      enabled: false,
      status: null,
    },
    billing_address_collection: null,
    cancel_url: "https://httpbin.org/post",
    client_reference_id: null,
    consent: null,
    consent_collection: null,
    created: 1690472483,
    currency: "usd",
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      shipping_address: null,
      submit: null,
    },
    customer: null,
    customer_creation: "if_required",
    customer_details: {
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      email: "stripe@example.com",
      name: "Jenny Rosen",
      phone: null,
      tax_exempt: "none",
      tax_ids: [],
    },
    customer_email: null,
    expires_at: 1690558883,
    invoice: null,
    invoice_creation: {
      enabled: false,
      invoice_data: {
        account_tax_ids: null,
        custom_fields: null,
        description: null,
        footer: null,
        metadata: {},
        rendering_options: null,
      },
    },
    livemode: false,
    locale: null,
    metadata: {},
    mode: "payment",
    payment_intent: "pi_3NYWJcI0XSgju2ur1bZTeRhR",
    payment_link: null,
    payment_method_collection: "always",
    payment_method_options: {},
    payment_method_types: ["card"],
    payment_status: "paid",
    phone_number_collection: {
      enabled: false,
    },
    recovered_from: null,
    setup_intent: null,
    shipping_address_collection: null,
    shipping_cost: null,
    shipping_details: null,
    shipping_options: [],
    status: "complete",
    submit_type: null,
    subscription: null,
    success_url: "https://httpbin.org/post",
    total_details: {
      amount_discount: 0,
      amount_shipping: 0,
      amount_tax: 0,
    },
    url: null,
  },
};

export const customerSubscriptionExample = {
  id: "test_subscription",
  name: "Mock Subscription",
  icon: "stripe",
  payload: {
    id: "sub_1NYWgUI0XSgju2urmVcglalG",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
    },
    billing_cycle_anchor: 1690473902,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1690473902,
    currency: "usd",
    current_period_end: 1693152302,
    current_period_start: 1690473902,
    customer: "cus_OLD6IR3D8CJasG",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: "list",
      data: [
        {
          id: "si_OLD6qgIKdp0wZO",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1690473903,
          metadata: {},
          plan: {
            id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 1500,
            amount_decimal: "1500",
            billing_scheme: "per_unit",
            created: 1690473902,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            nickname: null,
            product: "prod_OLD6aEjleFDUfA",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1690473902,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_OLD6aEjleFDUfA",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 1500,
            unit_amount_decimal: "1500",
          },
          quantity: 1,
          subscription: "sub_1NYWgUI0XSgju2urmVcglalG",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1NYWgUI0XSgju2urmVcglalG",
    },
    latest_invoice: "in_1NYWgUI0XSgju2urV5ZTEyIn",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 1500,
      amount_decimal: "1500",
      billing_scheme: "per_unit",
      created: 1690473902,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: "prod_OLD6aEjleFDUfA",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1690473902,
    status: "active",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
};

export const pausedSubscriptionExample = {
  id: "test_subscription",
  name: "Mock Subscription",
  icon: "stripe",
  payload: {
    id: "sub_1NYWgUI0XSgju2urmVcglalG",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
    },
    billing_cycle_anchor: 1690473902,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1690473902,
    currency: "usd",
    current_period_end: 1693152302,
    current_period_start: 1690473902,
    customer: "cus_OLD6IR3D8CJasG",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: "list",
      data: [
        {
          id: "si_OLD6qgIKdp0wZO",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1690473903,
          metadata: {},
          plan: {
            id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 1500,
            amount_decimal: "1500",
            billing_scheme: "per_unit",
            created: 1690473902,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            nickname: null,
            product: "prod_OLD6aEjleFDUfA",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1690473902,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_OLD6aEjleFDUfA",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 1500,
            unit_amount_decimal: "1500",
          },
          quantity: 1,
          subscription: "sub_1NYWgUI0XSgju2urmVcglalG",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1NYWgUI0XSgju2urmVcglalG",
    },
    latest_invoice: "in_1NYWgUI0XSgju2urV5ZTEyIn",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1NYWgUI0XSgju2ur3rwJGw1n",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 1500,
      amount_decimal: "1500",
      billing_scheme: "per_unit",
      created: 1690473902,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: "prod_OLD6aEjleFDUfA",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1690473902,
    status: "paused",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
};

export const cancelledSubscriptionExample = {
  id: "test_subscription",
  name: "Cancelled Subscription",
  icon: "stripe",
  payload: {
    id: "sub_1NYWmqI0XSgju2urM6J7U81g",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
    },
    billing_cycle_anchor: 1690474295,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1690474298,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: "cancellation_requested",
    },
    collection_method: "charge_automatically",
    created: 1690474295,
    currency: "usd",
    current_period_end: 1693152695,
    current_period_start: 1690474295,
    customer: "cus_OLDDzu7ZE2wLZB",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1690474298,
    items: {
      object: "list",
      data: [
        {
          id: "si_OLDDWvHquPJrro",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1690474296,
          metadata: {},
          plan: {
            id: "price_1NYWmpI0XSgju2ur8YboK1MK",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 1500,
            amount_decimal: "1500",
            billing_scheme: "per_unit",
            created: 1690474295,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            nickname: null,
            product: "prod_OLDDFHiTTQUoPT",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1NYWmpI0XSgju2ur8YboK1MK",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1690474295,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_OLDDFHiTTQUoPT",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 1500,
            unit_amount_decimal: "1500",
          },
          quantity: 1,
          subscription: "sub_1NYWmqI0XSgju2urM6J7U81g",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1NYWmqI0XSgju2urM6J7U81g",
    },
    latest_invoice: "in_1NYWmqI0XSgju2ur1YkCeiE3",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1NYWmpI0XSgju2ur8YboK1MK",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 1500,
      amount_decimal: "1500",
      billing_scheme: "per_unit",
      created: 1690474295,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: "prod_OLDDFHiTTQUoPT",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1690474295,
    status: "canceled",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
};

export const updatedSubscriptionExample = {
  id: "test_subscription",
  name: "Updated Subscription",
  icon: "stripe",
  payload: {
    id: "sub_1NYWr9I0XSgju2urREzIjypw",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
    },
    billing_cycle_anchor: 1690474563,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1690474563,
    currency: "usd",
    current_period_end: 1693152963,
    current_period_start: 1690474563,
    customer: "cus_OLDHaOoGMJKpbQ",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: "list",
      data: [
        {
          id: "si_OLDHbwqQpcI7wJ",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1690474564,
          metadata: {},
          plan: {
            id: "price_1NYWr9I0XSgju2urK88vlVrN",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 1500,
            amount_decimal: "1500",
            billing_scheme: "per_unit",
            created: 1690474563,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            nickname: null,
            product: "prod_OLDHCaYW7Sp4Xg",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1NYWr9I0XSgju2urK88vlVrN",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1690474563,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_OLDHCaYW7Sp4Xg",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 1500,
            unit_amount_decimal: "1500",
          },
          quantity: 1,
          subscription: "sub_1NYWr9I0XSgju2urREzIjypw",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1NYWr9I0XSgju2urREzIjypw",
    },
    latest_invoice: "in_1NYWr9I0XSgju2uro3uB0RuT",
    livemode: false,
    metadata: {
      foo: "bar",
    },
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1NYWr9I0XSgju2urK88vlVrN",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 1500,
      amount_decimal: "1500",
      billing_scheme: "per_unit",
      created: 1690474563,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: "prod_OLDHCaYW7Sp4Xg",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1690474563,
    status: "active",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
};
