-- CreateEnum
CREATE TYPE "TaskRunStatus" AS ENUM ('PENDING', 'EXECUTING', 'WAITING_TO_RESUME', 'RETRYING_AFTER_FAILURE', 'PAUSED', 'CANCELED', 'COMPLETED_SUCCESSFULLY', 'COMPLETED_WITH_ERRORS');

-- AlterTable
ALTER TABLE "TaskRun" ADD COLUMN     "status" "TaskRunStatus" NOT NULL DEFAULT 'PENDING';
