trigger:
  name: trigger
  replicaCount: 2
  image:
    repository: ghcr.io/triggerdotdev/trigger.dev
    tag: "latest" 
    pullPolicy: Always
  env:
    ENCRYPTION_KEY: "b1ebe43a6a6e24b2aa8fa0707d3890e3"
    MAGIC_LINK_SECRET: "842727396bcee22da68518f959c5730b"

ingress:
  nginx:
    enabled: false #<-- if you would like to install nginx along with Trigger.dev
