export const checkoutCompletedSuccess = {
  id: "cs_test_a1EgJwW6lYFfhmnIYz49gIjMrt4T9ppRZsh9pohheMDg5p5vp7tsKxr9tV",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 3000,
  amount_total: 3000,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  billing_address_collection: null,
  cancel_url: "https://httpbin.org/post",
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  created: 1678198980,
  currency: "usd",
  custom_fields: [],
  custom_text: {
    shipping_address: null,
    submit: null,
  },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: null,
      country: null,
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: "stripe@example.com",
    name: null,
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1678285379,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {},
  mode: "payment",
  payment_intent: "pi_3Mj1PtGHlQRWA8Cg0YFQ7ukK",
  payment_link: null,
  payment_method_collection: "always",
  payment_method_options: {},
  payment_method_types: ["card"],
  payment_status: "paid",
  phone_number_collection: {
    enabled: false,
  },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "https://httpbin.org/post",
  total_details: {
    amount_discount: 0,
    amount_shipping: 0,
    amount_tax: 0,
  },
  url: null,
};
