// GENERATED by scripts/generate-ai-trql-schema.ts — do not edit by hand.
// Regenerate after changing app/v3/querySchemas.ts:
//   pnpm exec tsx apps/webapp/scripts/generate-ai-trql-schema.ts

export interface TrqlColumn {
  name: string;
  type: string;
  description?: string;
  allowedValues?: string[];
}

export interface TrqlTable {
  name: string;
  description: string;
  timeColumn?: string;
  columns: TrqlColumn[];
}

export const trqlTables: TrqlTable[] = [
  {
    "name": "runs",
    "description": "Task runs - stores all task execution records",
    "timeColumn": "triggered_at",
    "columns": [
      {
        "name": "run_id",
        "type": "String",
        "description": "A unique ID for a run. They always start with `run_`, e.g., run_cm1a2b3c4d5e6f7g8h9i"
      },
      {
        "name": "environment",
        "type": "String",
        "description": "The environment slug"
      },
      {
        "name": "project",
        "type": "String",
        "description": "The project reference, they always start with `proj_`."
      },
      {
        "name": "environment_type",
        "type": "LowCardinality(String)",
        "description": "Environment type",
        "allowedValues": [
          "PRODUCTION",
          "STAGING",
          "DEVELOPMENT",
          "PREVIEW"
        ]
      },
      {
        "name": "attempt_count",
        "type": "UInt8",
        "description": "Number of attempts (starts at 1)"
      },
      {
        "name": "status",
        "type": "LowCardinality(String)",
        "description": "Run status",
        "allowedValues": [
          "Delayed",
          "Queued",
          "Pending version",
          "Pending version",
          "Dequeued",
          "Executing",
          "Waiting",
          "Reattempting",
          "Paused",
          "Canceled",
          "Interrupted",
          "Completed",
          "Failed",
          "System failure",
          "Crashed",
          "Expired",
          "Timed out"
        ]
      },
      {
        "name": "is_finished",
        "type": "UInt8",
        "description": "Whether the run is finished. This includes failed and successful runs. (0 or 1)"
      },
      {
        "name": "task_identifier",
        "type": "String",
        "description": "Task identifier/slug"
      },
      {
        "name": "queue",
        "type": "String",
        "description": "Queue name"
      },
      {
        "name": "batch_id",
        "type": "String",
        "description": "Batch ID (if part of a batch)"
      },
      {
        "name": "root_run_id",
        "type": "String",
        "description": "Root run ID (for child runs)"
      },
      {
        "name": "parent_run_id",
        "type": "String",
        "description": "Parent run ID (for child runs)"
      },
      {
        "name": "depth",
        "type": "UInt8",
        "description": "Nesting depth (0 for root runs)"
      },
      {
        "name": "is_root_run",
        "type": "UInt8",
        "description": "Whether this is a root run (0 or 1)"
      },
      {
        "name": "is_child_run",
        "type": "UInt8",
        "description": "Whether this is a child run (0 or 1)"
      },
      {
        "name": "idempotency_key",
        "type": "String",
        "description": "Idempotency key (available from 4.3.3)"
      },
      {
        "name": "idempotency_key_scope",
        "type": "String",
        "description": "The idempotency key scope determines whether a task should be considered unique within a parent run, a specific attempt, or globally. An empty value means there's no idempotency key set (available from 4.3.3).",
        "allowedValues": [
          "global",
          "run",
          "attempt"
        ]
      },
      {
        "name": "region",
        "type": "String",
        "description": "Region"
      },
      {
        "name": "triggered_at",
        "type": "DateTime64",
        "description": "When the run was triggered."
      },
      {
        "name": "queued_at",
        "type": "Nullable(DateTime64)",
        "description": "When the run was added to the queue. This is normally the same time as the triggered_at time, unless a delay is passed in or it's a scheduled run."
      },
      {
        "name": "dequeued_at",
        "type": "Nullable(DateTime64)",
        "description": "When the run was dequeued for execution. This happens when there is available concurrency to execute your run."
      },
      {
        "name": "executed_at",
        "type": "Nullable(DateTime64)",
        "description": "When execution of the run began."
      },
      {
        "name": "completed_at",
        "type": "Nullable(DateTime64)",
        "description": "When the run completed"
      },
      {
        "name": "delay_until",
        "type": "Nullable(DateTime64)",
        "description": "Delayed execution until this time"
      },
      {
        "name": "has_delay",
        "type": "UInt8",
        "description": "Whether the run had a delay passed in"
      },
      {
        "name": "expired_at",
        "type": "Nullable(DateTime64)",
        "description": "If there was a TTL on the run, this is when the run \"expired\". By default dev runs have a TTL of 10 minutes."
      },
      {
        "name": "ttl",
        "type": "String",
        "description": "The TTL string for expiration – by default dev runs have a TTL of '10m'."
      },
      {
        "name": "execution_duration",
        "type": "Nullable(Int64)",
        "description": "The time between starting to execute and completing. This includes any time spent waiting (it is not compute time, use `usage_duration` for that)."
      },
      {
        "name": "total_duration",
        "type": "Nullable(Int64)",
        "description": "The time between being triggered and completing (if it has). This includes any time spent waiting (it is not compute time, use `usage_duration` for that)."
      },
      {
        "name": "queued_duration",
        "type": "Nullable(Int64)",
        "description": "The time between being queued and dequeued. Remember you need enough available concurrency for runs to be dequeued and start executing."
      },
      {
        "name": "usage_duration",
        "type": "UInt32",
        "description": "Compute usage duration in milliseconds."
      },
      {
        "name": "compute_cost",
        "type": "Float64",
        "description": "Compute cost in dollars"
      },
      {
        "name": "invocation_cost",
        "type": "Float64",
        "description": "Invocation cost in dollars – the cost to start a run."
      },
      {
        "name": "total_cost",
        "type": "Float64",
        "description": "Total cost in dollars (compute_cost + invocation_cost)"
      },
      {
        "name": "output",
        "type": "JSON",
        "description": "The data you returned from the task."
      },
      {
        "name": "error",
        "type": "JSON",
        "description": "If a run completely failed (after all attempts) then this error will be populated."
      },
      {
        "name": "tags",
        "type": "Array(String)",
        "description": "Tags you have added to the run."
      },
      {
        "name": "task_version",
        "type": "String",
        "description": "The version of your code in reverse date format."
      },
      {
        "name": "sdk_version",
        "type": "String",
        "description": "The SDK package version for this run."
      },
      {
        "name": "cli_version",
        "type": "String",
        "description": "The CLI package version for this run."
      },
      {
        "name": "machine",
        "type": "LowCardinality(String)",
        "description": "The machine that the run executed on.",
        "allowedValues": [
          "micro",
          "small-1x",
          "small-2x",
          "medium-1x",
          "medium-2x",
          "large-1x",
          "large-2x"
        ]
      },
      {
        "name": "is_test",
        "type": "UInt8",
        "description": "Whether this is a test run (0 or 1)"
      },
      {
        "name": "is_warm_start",
        "type": "Nullable(UInt8)",
        "description": "Whether this run used a warm start vs a cold start."
      },
      {
        "name": "concurrency_key",
        "type": "String",
        "description": "The concurrency key you passed in when triggering the run."
      },
      {
        "name": "max_duration",
        "type": "Nullable(UInt32)",
        "description": "The maximum allowed compute duration for this run in seconds. If the run exceeds this duration, the run will fail with an error. Can be set on an individual task, in the trigger.config, or per-run when triggering."
      },
      {
        "name": "bulk_action_group_ids",
        "type": "Array(String)",
        "description": "Any bulk actions that operated on this run."
      }
    ]
  },
  {
    "name": "metrics",
    "description": "Host and runtime metrics collected during task execution",
    "timeColumn": "bucket_start",
    "columns": [
      {
        "name": "environment",
        "type": "String",
        "description": "The environment slug"
      },
      {
        "name": "project",
        "type": "String",
        "description": "The project reference, they always start with `proj_`."
      },
      {
        "name": "metric_name",
        "type": "LowCardinality(String)",
        "description": "The name of the metric (e.g. process.cpu.utilization, system.memory.usage)"
      },
      {
        "name": "metric_type",
        "type": "LowCardinality(String)",
        "description": "The type of metric",
        "allowedValues": [
          "gauge",
          "sum",
          "histogram"
        ]
      },
      {
        "name": "machine_id",
        "type": "String",
        "description": "The machine ID that produced this metric"
      },
      {
        "name": "bucket_start",
        "type": "DateTime",
        "description": "The start of the 10-second aggregation bucket"
      },
      {
        "name": "metric_value",
        "type": "Float64",
        "description": "The metric value"
      },
      {
        "name": "attributes",
        "type": "JSON",
        "description": "JSON attributes attached to the metric data point."
      },
      {
        "name": "run_id",
        "type": "String",
        "description": "The run ID associated with this metric"
      },
      {
        "name": "task_identifier",
        "type": "String",
        "description": "Task identifier/slug"
      },
      {
        "name": "attempt_number",
        "type": "UInt64",
        "description": "The attempt number for this metric"
      },
      {
        "name": "machine_name",
        "type": "String",
        "description": "The machine preset used for execution",
        "allowedValues": [
          "micro",
          "small-1x",
          "small-2x",
          "medium-1x",
          "medium-2x",
          "large-1x",
          "large-2x"
        ]
      },
      {
        "name": "environment_type",
        "type": "String",
        "description": "Environment type",
        "allowedValues": [
          "PRODUCTION",
          "STAGING",
          "DEVELOPMENT",
          "PREVIEW"
        ]
      },
      {
        "name": "worker_id",
        "type": "String",
        "description": "The worker ID that produced this metric"
      },
      {
        "name": "worker_version",
        "type": "String",
        "description": "The worker version that produced this metric"
      }
    ]
  },
  {
    "name": "llm_metrics",
    "description": "LLM metrics: token usage, cost, performance, and behavior from GenAI spans",
    "timeColumn": "start_time",
    "columns": [
      {
        "name": "environment",
        "type": "String",
        "description": "The environment slug"
      },
      {
        "name": "project",
        "type": "String",
        "description": "The project reference, they always start with `proj_`."
      },
      {
        "name": "run_id",
        "type": "String",
        "description": "The run ID"
      },
      {
        "name": "trace_id",
        "type": "String",
        "description": "The trace ID"
      },
      {
        "name": "span_id",
        "type": "String",
        "description": "The span ID"
      },
      {
        "name": "task_identifier",
        "type": "LowCardinality(String)",
        "description": "The task identifier"
      },
      {
        "name": "gen_ai_system",
        "type": "LowCardinality(String)",
        "description": "AI provider (e.g. openai, anthropic)"
      },
      {
        "name": "request_model",
        "type": "String",
        "description": "The model name requested"
      },
      {
        "name": "response_model",
        "type": "String",
        "description": "The model name returned by the provider"
      },
      {
        "name": "operation_id",
        "type": "LowCardinality(String)",
        "description": "Operation type (e.g. ai.streamText.doStream, ai.generateText.doGenerate)"
      },
      {
        "name": "finish_reason",
        "type": "LowCardinality(String)",
        "description": "Why the LLM stopped generating (e.g. stop, tool-calls, length)"
      },
      {
        "name": "cost_source",
        "type": "LowCardinality(String)",
        "description": "Where cost data came from (registry, gateway, openrouter)"
      },
      {
        "name": "input_tokens",
        "type": "UInt64",
        "description": "Number of input tokens"
      },
      {
        "name": "output_tokens",
        "type": "UInt64",
        "description": "Number of output tokens"
      },
      {
        "name": "total_tokens",
        "type": "UInt64",
        "description": "Total token count"
      },
      {
        "name": "cached_read_tokens",
        "type": "UInt64",
        "description": "Input tokens served from the provider's prompt cache (cheaper than regular input tokens). Supported by Anthropic and OpenAI."
      },
      {
        "name": "cache_creation_tokens",
        "type": "UInt64",
        "description": "Input tokens written to create a new prompt cache entry. Supported by Anthropic."
      },
      {
        "name": "reasoning_tokens",
        "type": "UInt64",
        "description": "Tokens used for chain-of-thought reasoning (e.g. OpenAI o-series, DeepSeek R1). These count toward output but are not visible in the response."
      },
      {
        "name": "input_cost",
        "type": "Decimal64(12)",
        "description": "Input cost in USD (from pricing registry)"
      },
      {
        "name": "output_cost",
        "type": "Decimal64(12)",
        "description": "Output cost in USD (from pricing registry)"
      },
      {
        "name": "total_cost",
        "type": "Decimal64(12)",
        "description": "Total cost in USD"
      },
      {
        "name": "cached_read_cost",
        "type": "Decimal64(12)",
        "description": "Cost of cached input tokens (discounted vs regular input). Only present when the pricing tier has a separate cached input price."
      },
      {
        "name": "cache_creation_cost",
        "type": "Decimal64(12)",
        "description": "Cost of tokens written to create a prompt cache entry."
      },
      {
        "name": "provider_cost",
        "type": "Decimal64(12)",
        "description": "Provider-reported cost in USD (from gateway or openrouter)"
      },
      {
        "name": "ms_to_first_chunk",
        "type": "Float64",
        "description": "Time to first chunk in milliseconds (TTFC)"
      },
      {
        "name": "tokens_per_second",
        "type": "Float64",
        "description": "Average output tokens per second"
      },
      {
        "name": "pricing_tier_name",
        "type": "LowCardinality(String)",
        "description": "The matched pricing tier name"
      },
      {
        "name": "start_time",
        "type": "DateTime64(9)",
        "description": "When the LLM call started"
      },
      {
        "name": "duration",
        "type": "UInt64",
        "description": "Span duration in nanoseconds"
      },
      {
        "name": "prompt_slug",
        "type": "LowCardinality(String)",
        "description": "The managed prompt slug used for this LLM call"
      },
      {
        "name": "prompt_version",
        "type": "UInt32",
        "description": "The managed prompt version number used for this LLM call"
      },
      {
        "name": "metadata",
        "type": "Map(LowCardinality(String), String)",
        "description": "Key-value metadata from run tags (key:value format) and AI SDK telemetry metadata. Access keys with dot notation (metadata.userId) or bracket syntax (metadata['userId'])."
      }
    ]
  },
  {
    "name": "llm_models",
    "description": "Cross-tenant model performance aggregates: calls, cost, latency, and throughput per model per minute. No tenant-specific data.",
    "timeColumn": "minute",
    "columns": [
      {
        "name": "response_model",
        "type": "String",
        "description": "The model name as returned by the provider"
      },
      {
        "name": "base_response_model",
        "type": "String",
        "description": "The base model name with dated variants grouped"
      },
      {
        "name": "gen_ai_system",
        "type": "String",
        "description": "The AI provider system identifier"
      },
      {
        "name": "minute",
        "type": "DateTime",
        "description": "Aggregation time bucket (per minute)"
      },
      {
        "name": "call_count",
        "type": "UInt64",
        "description": "Number of LLM calls in this time bucket"
      },
      {
        "name": "total_input_tokens",
        "type": "UInt64",
        "description": "Total input tokens consumed"
      },
      {
        "name": "total_output_tokens",
        "type": "UInt64",
        "description": "Total output tokens generated"
      },
      {
        "name": "total_cost",
        "type": "Float64",
        "description": "Total cost in USD"
      },
      {
        "name": "ttfc_quantiles",
        "type": "String",
        "description": "Time to first chunk quantile state. Use quantilesMerge(0.5)(ttfc_quantiles)[1] AS ttfc_p50 in queries."
      },
      {
        "name": "tps_quantiles",
        "type": "String",
        "description": "Tokens per second quantile state. Use quantilesMerge(0.5)(tps_quantiles)[1] AS tps_p50 in queries."
      },
      {
        "name": "duration_quantiles",
        "type": "String",
        "description": "Duration quantile state. Use quantilesMerge(0.5)(duration_quantiles)[1] AS duration_p50 in queries."
      }
    ]
  }
];
