receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/internal:
    protocols:
      http:
        endpoint: 0.0.0.0:4319

processors:
  batch:

exporters:
  otlp/honey:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "hcaik_01hps80a4qjsnnp6t757r5r70vqm8fwd7tejqdthzk9z98zsdn6ejwzazb"
  logging:
    verbosity: normal
  otlphttp:
    endpoint: "http://host.docker.internal:3030/otel"
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    traces/internal:
      receivers: [otlp/internal]
      processors: [batch]
      exporters: [otlp/honey]
