receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "7e999faWC62210wKXMAHNM"
  logging:
    verbosity: normal
  otlphttp:
    endpoint: "http://host.docker.internal:3030/otel"
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlphttp]
