-- AlterTable
ALTER TABLE "TaskEvent" ADD COLUMN     "cpuTimeMs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wallTimeMs" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "TaskRunAttempt" ADD COLUMN     "cpuTimeMs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wallTimeMs" INTEGER NOT NULL DEFAULT 0;
