/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: ["**/.*"],
  devServerPort: 8002,
  serverDependenciesToBundle: [
    "pretty-bytes",
    "marked",
    "@cfworker/json-schema",
    "@nangohq/pizzly-frontend",
    "@nangohq/pizzly-node",
    "axios",
    "internal-platform",
    "internal-bridge",
    "integration-catalog",
    "@trigger.dev/github",
    "@trigger.dev/slack",
    "@trigger.dev/resend",
    "@trigger.dev/shopify",
    "@trigger.dev/common-schemas",
    "@trigger.dev/sdk",
    "@trigger.dev/integration-sdk",
    "emails",
    "internal-pulsar",
    "@octokit/webhooks",
  ],
  watchPaths: async () => {
    return [
      "../../packages/internal-platform/src/**/*",
      "../../packages/internal-bridge/src/**/*",
      "../../packages/common-schemas/src/**/*",
      "../../packages/integration-catalog/src/**/*",
      "../../packages/emails/src/**/*",
      "../../packages/internal-pulsar/src/**/*",
      "../../packages/internal-platform/src/**/*",
      "../../integrations/github/src/**/*",
      "../../integrations/slack/src/**/*",
      "../../integrations/resend/src/**/*",
      "../../integrations/shopify/src/**/*",
    ];
  },
};
