{{- if and .Values.clickhouse.enabled (not .Values.clickhouse.external) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "trigger-v4.fullname" . }}-clickhouse
  labels:
    {{- $component := "clickhouse" }}
    {{- include "trigger-v4.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "trigger-v4.fullname" . }}-clickhouse-headless
  selector:
    matchLabels:
      {{- include "trigger-v4.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.clickhouse.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trigger-v4.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 8 }}
    spec:
      {{- with .Values.clickhouse.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clickhouse
          {{- with .Values.clickhouse.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.clickhouse.image.registry }}/{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          ports:
            - name: native
              containerPort: {{ .Values.clickhouse.service.ports.native }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.clickhouse.service.ports.http }}
              protocol: TCP
          env:
            - name: CLICKHOUSE_ADMIN_USER
              value: {{ .Values.clickhouse.auth.adminUser | quote }}
            - name: CLICKHOUSE_ADMIN_PASSWORD
              value: {{ .Values.clickhouse.auth.adminPassword | quote }}
            {{- with .Values.clickhouse.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - clickhouse-client
                - --host
                - localhost
                - --port
                - {{ .Values.clickhouse.service.ports.native | quote }}
                - --user
                - {{ .Values.clickhouse.auth.adminUser }}
                - --password
                - {{ .Values.clickhouse.auth.adminPassword }}
                - --query
                - "SELECT 1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - clickhouse-client
                - --host
                - localhost
                - --port
                - {{ .Values.clickhouse.service.ports.native | quote }}
                - --user
                - {{ .Values.clickhouse.auth.adminUser }}
                - --password
                - {{ .Values.clickhouse.auth.adminPassword }}
                - --query
                - "SELECT 1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 5
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          volumeMounts:
            - name: clickhouse-data
              mountPath: /bitnami/clickhouse
            - name: clickhouse-config
              mountPath: /bitnami/clickhouse/etc/config.d/override.xml
              subPath: override.xml
              readOnly: true
      volumes:
        - name: clickhouse-config
          configMap:
            name: {{ include "trigger-v4.fullname" . }}-clickhouse-config
        {{- if not .Values.clickhouse.persistence.enabled }}
        - name: clickhouse-data
          emptyDir: {}
        {{- end }}
  {{- if .Values.clickhouse.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
        labels:
          {{- $component := "clickhouse" }}
          {{- include "trigger-v4.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.clickhouse.persistence.size }}
        {{- $storageClass := .Values.clickhouse.persistence.storageClass | default .Values.global.storageClass }}
        {{- if $storageClass }}
        storageClassName: {{ $storageClass | quote }}
        {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trigger-v4.fullname" . }}-clickhouse-headless
  labels:
    {{- $component := "clickhouse" }}
    {{- include "trigger-v4.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: native
      port: {{ .Values.clickhouse.service.ports.native }}
      targetPort: native
      protocol: TCP
    - name: http
      port: {{ .Values.clickhouse.service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "trigger-v4.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trigger-v4.fullname" . }}-clickhouse
  labels:
    {{- $component := "clickhouse" }}
    {{- include "trigger-v4.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - name: native
      port: {{ .Values.clickhouse.service.ports.native }}
      targetPort: native
      protocol: TCP
    - name: http
      port: {{ .Values.clickhouse.service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "trigger-v4.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
{{- end }}