import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

type Row = [
  id: string,
  label: string,
  category: string,
  preset: string | null,
  scheme: string,
  popularity: string,
  sampleSource: string,
  docsUrl: string,
];

const PRESETS = new Set(["stripe", "github", "svix", "square", "discord"]);

const DOD: Record<string, string[]> = {
  "first-class": ["registryEntry", "samples", "roundTrip", "producer"],
  "sample-only": ["registryEntry", "samples"],
};

const rows: Row[] = [
  [
    "openai",
    "OpenAI",
    "ai-platform",
    "svix",
    "standard-webhooks",
    "high",
    "handauthored",
    "https://platform.openai.com/docs/guides/webhooks",
  ],
  [
    "anthropic",
    "Anthropic (Claude)",
    "ai-platform",
    "svix",
    "standard-webhooks",
    "high",
    "handauthored",
    "https://platform.claude.com/docs/en/managed-agents/webhooks",
  ],
  [
    "replicate",
    "Replicate",
    "ai-platform",
    "svix",
    "standard-webhooks",
    "medium",
    "handauthored",
    "https://replicate.com/docs/topics/webhooks/verify-webhook",
  ],
  [
    "recall-ai",
    "Recall.ai",
    "ai-platform",
    "svix",
    "standard-webhooks",
    "medium",
    "handauthored",
    "https://docs.recall.ai/docs/authenticating-requests-from-recallai",
  ],
  [
    "clerk",
    "Clerk",
    "auth-identity",
    "svix",
    "svix",
    "high",
    "handauthored",
    "https://clerk.com/docs/guides/development/webhooks/overview",
  ],
  [
    "resend",
    "Resend",
    "email",
    "svix",
    "svix",
    "high",
    "handauthored",
    "https://resend.com/docs/dashboard/webhooks/introduction",
  ],
  [
    "brex",
    "Brex",
    "fintech",
    "svix",
    "svix",
    "medium",
    "handauthored",
    "https://developer.brex.com/docs/webhooks/",
  ],
  [
    "gitlab",
    "GitLab",
    "source-control",
    "svix",
    "standard-webhooks",
    "high",
    "hookdeck",
    "https://docs.gitlab.com/user/project/integrations/webhooks/",
  ],
  [
    "github",
    "GitHub",
    "source-control",
    "github",
    "hmac-sha256",
    "high",
    "hookdeck",
    "https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries",
  ],
  [
    "whatsapp",
    "WhatsApp (Meta)",
    "communication",
    "github",
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developers.facebook.com/docs/whatsapp/cloud-api/guides/set-up-webhooks/",
  ],
  [
    "jira",
    "Jira",
    "pm",
    "github",
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
  ],
  [
    "stripe",
    "Stripe",
    "payments",
    "stripe",
    "stripe",
    "high",
    "hookdeck",
    "https://docs.stripe.com/webhooks",
  ],
  [
    "square",
    "Square",
    "payments",
    "square",
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://developer.squareup.com/docs/webhooks/step3validate",
  ],
  [
    "discord",
    "Discord",
    "communication",
    "discord",
    "ed25519",
    "high",
    "handauthored",
    "https://docs.discord.com/developers/events/webhook-events",
  ],

  [
    "elevenlabs",
    "ElevenLabs",
    "voice",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://elevenlabs.io/docs/eleven-agents/workflows/post-call-webhooks",
  ],
  [
    "vapi",
    "Vapi",
    "voice",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://docs.vapi.ai/server-url/server-authentication",
  ],
  [
    "retell",
    "Retell AI",
    "voice",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://docs.retellai.com/features/secure-webhook",
  ],
  [
    "assemblyai",
    "AssemblyAI",
    "ai-platform",
    null,
    "shared-secret",
    "medium",
    "handauthored",
    "https://www.assemblyai.com/docs/concepts/webhooks",
  ],
  [
    "deepgram",
    "Deepgram",
    "ai-platform",
    null,
    "none-or-ip-allowlist",
    "medium",
    "handauthored",
    "https://developers.deepgram.com/docs/callback",
  ],
  [
    "slack",
    "Slack",
    "communication",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://docs.slack.dev/authentication/verifying-requests-from-slack/",
  ],
  [
    "telegram",
    "Telegram",
    "communication",
    null,
    "shared-secret",
    "medium",
    "handauthored",
    "https://core.telegram.org/bots/api#setwebhook",
  ],
  [
    "twilio",
    "Twilio",
    "communication",
    null,
    "hmac-sha1",
    "high",
    "handauthored",
    "https://www.twilio.com/docs/usage/webhooks/webhooks-security",
  ],
  [
    "zoom",
    "Zoom",
    "communication",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developers.zoom.us/docs/api/webhooks/",
  ],
  [
    "sendgrid",
    "SendGrid",
    "email",
    null,
    "ecdsa",
    "high",
    "handauthored",
    "https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/getting-started-event-webhook-security-features",
  ],
  [
    "postmark",
    "Postmark",
    "email",
    null,
    "basic",
    "medium",
    "handauthored",
    "https://postmarkapp.com/developer/webhooks/inbound-webhook",
  ],
  [
    "zendesk",
    "Zendesk",
    "support",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developer.zendesk.com/documentation/webhooks/verifying/",
  ],
  [
    "intercom",
    "Intercom",
    "support",
    null,
    "hmac-sha1",
    "high",
    "handauthored",
    "https://developers.intercom.com/docs/references/webhooks/webhook-models",
  ],
  [
    "cal-com",
    "Cal.com",
    "calendar-scheduling",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://cal.com/docs/developing/guides/automation/webhooks",
  ],
  [
    "calendly",
    "Calendly",
    "calendar-scheduling",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
  ],
  [
    "linear",
    "Linear",
    "pm",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://linear.app/developers/webhooks",
  ],
  [
    "sentry",
    "Sentry",
    "observability",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://docs.sentry.io/product/integrations/integration-platform/webhooks/",
  ],
  [
    "vercel",
    "Vercel",
    "hosting-infra",
    null,
    "hmac-sha1",
    "high",
    "handauthored",
    "https://vercel.com/docs/webhooks",
  ],
  [
    "pagerduty",
    "PagerDuty",
    "observability",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
  ],
  [
    "auth0",
    "Auth0",
    "auth-identity",
    null,
    "bearer",
    "high",
    "handauthored",
    "https://auth0.com/docs/customize/log-streams/custom-log-streams",
  ],
  [
    "workos",
    "WorkOS",
    "auth-identity",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://workos.com/docs/events/data-syncing/webhooks",
  ],
  [
    "supabase",
    "Supabase",
    "hosting-infra",
    null,
    "shared-secret",
    "high",
    "handauthored",
    "https://supabase.com/docs/guides/database/webhooks",
  ],
  [
    "notion",
    "Notion",
    "productivity",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developers.notion.com/reference/webhooks",
  ],
  [
    "attio",
    "Attio",
    "crm",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://docs.attio.com/rest-api/guides/webhooks",
  ],
  [
    "close-crm",
    "Close",
    "crm",
    null,
    "hmac-sha256",
    "medium",
    "handauthored",
    "https://developer.close.com/topics/webhooks/",
  ],
  [
    "hubspot",
    "HubSpot",
    "crm",
    null,
    "hmac-sha256",
    "high",
    "hookdeck",
    "https://developers.hubspot.com/docs/guides/api/app-management/webhooks",
  ],
  [
    "typeform",
    "Typeform",
    "forms",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://www.typeform.com/developers/webhooks/secure-your-webhooks/",
  ],
  [
    "docusign",
    "DocuSign",
    "e-signature",
    null,
    "hmac-sha256",
    "high",
    "handauthored",
    "https://developers.docusign.com/platform/webhooks/connect/",
  ],
  [
    "shopify",
    "Shopify",
    "commerce",
    null,
    "hmac-sha256",
    "high",
    "hookdeck",
    "https://shopify.dev/docs/apps/build/webhooks/verify-deliveries",
  ],
  [
    "plaid",
    "Plaid",
    "fintech",
    null,
    "jwt",
    "high",
    "handauthored",
    "https://plaid.com/docs/api/webhooks/webhook-verification/",
  ],
];

const popRank: Record<string, number> = { high: 0, "medium-high": 1, medium: 2, low: 3 };

const providers = rows.map(
  ([id, label, category, preset, scheme, popularity, sampleSource, docsUrl]) => {
    const tier = preset ? "first-class" : "sample-only";
    const checklist = Object.fromEntries(DOD[tier].map((k) => [k, false]));
    return {
      id,
      label,
      category,
      tier,
      preset,
      signatureScheme: scheme,
      aiRelevance: "high",
      popularity,
      sampleSource,
      docsUrl,
      status: "not-started",
      owner: null,
      checklist,
      notes: "",
    };
  }
);

providers.sort((a, b) => {
  const t = (a.tier === "first-class" ? 0 : 1) - (b.tier === "first-class" ? 0 : 1);
  if (t !== 0) return t;
  const p = (popRank[a.popularity] ?? 9) - (popRank[b.popularity] ?? 9);
  if (p !== 0) return p;
  return a.label.localeCompare(b.label);
});

const seen = new Set<string>();
for (const p of providers) {
  if (seen.has(p.id)) throw new Error(`duplicate provider id: ${p.id}`);
  seen.add(p.id);
  if (p.preset && !PRESETS.has(p.preset)) throw new Error(`unknown preset ${p.preset} on ${p.id}`);
}

const catalog = {
  release: "webhooks-v1",
  scope: "ai-agent-first",
  updatedAt: null,
  definitionOfDone: DOD,
  statusValues: ["not-started", "in-progress", "complete", "blocked"],
  providers,
};

const outPath = fileURLToPath(new URL("./providers.json", import.meta.url));
writeFileSync(outPath, JSON.stringify(catalog, null, 2) + "\n");
console.log(`Wrote ${providers.length} providers to providers.json`);
console.log(`  first-class: ${providers.filter((p) => p.tier === "first-class").length}`);
console.log(`  sample-only: ${providers.filter((p) => p.tier === "sample-only").length}`);
