import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const srcDir = fileURLToPath(new URL("../src/", import.meta.url));

const alias = (base: string) => base.replace(/[^a-zA-Z0-9]/g, "_");

const listModules = (dir: string, exclude: string[]) =>
  readdirSync(new URL(`../src/${dir}/`, import.meta.url))
    .filter((f) => f.endsWith(".ts") && !exclude.includes(f))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();

const banner = "/** GENERATED by catalog/build-aggregates.ts. Do not edit by hand. */";

const registryModules = listModules("registry", ["types.ts", "index.ts"]);
const registryImports = registryModules
  .map((m) => `import { entry as e_${alias(m)} } from "./${m}.js";`)
  .join("\n");
const registryList = registryModules.map((m) => `e_${alias(m)}`).join(", ");
const registryOut = `${banner}
import { type ProviderRegistryEntry } from "./types.js";
${registryImports}

export const registryEntries: ProviderRegistryEntry[] = [${registryList}];

export const registry: Record<string, ProviderRegistryEntry> = Object.fromEntries(
  registryEntries.map((e) => [e.id, e])
);

export function getProvider(id: string): ProviderRegistryEntry | undefined {
  return registry[id];
}
`;
writeFileSync(new URL("./registry/index.ts", `file://${srcDir}`), registryOut);

const handAuthoredModules = listModules("handAuthored", ["index.ts"]);
const handImports = handAuthoredModules
  .map((m) => `import { samples as s_${alias(m)} } from "./${m}.js";`)
  .join("\n");
const handSpread = handAuthoredModules.map((m) => `...s_${alias(m)}`).join(", ");
const handOut = `${banner}
import { type SampleRecord } from "../sampleRecord.js";
${handImports}

export const handAuthoredSamples: SampleRecord[] = [${handSpread}];
`;
writeFileSync(new URL("./handAuthored/index.ts", `file://${srcDir}`), handOut);

console.log(
  `Aggregated ${registryModules.length} registry entries, ${handAuthoredModules.length} hand-authored sample modules`
);
