export const RUN_QUEUE_RESUME_PRIORITY_TIMESTAMP_OFFSET = 31_556_952 * 1000; // 1 year
export const RUN_QUEUE_DELAYED_REQUEUE_THRESHOLD_IN_MS = 500;
export const RUN_QUEUE_SCHEDULED_REQUEUE_AVAILABLE_AT_THRESHOLD_IN_MS = 500;
