/** GENERATED by catalog/build-aggregates.ts. Do not edit by hand. */
import { type ProviderRegistryEntry } from "./types.js";
import { entry as e_adyen } from "./adyen.js";
import { entry as e_anthropic } from "./anthropic.js";
import { entry as e_assemblyai } from "./assemblyai.js";
import { entry as e_attio } from "./attio.js";
import { entry as e_auth0 } from "./auth0.js";
import { entry as e_bigcommerce } from "./bigcommerce.js";
import { entry as e_bitbucket } from "./bitbucket.js";
import { entry as e_brex } from "./brex.js";
import { entry as e_cal_com } from "./cal-com.js";
import { entry as e_calendly } from "./calendly.js";
import { entry as e_checkout } from "./checkout.js";
import { entry as e_clerk } from "./clerk.js";
import { entry as e_close_crm } from "./close-crm.js";
import { entry as e_commercelayer } from "./commercelayer.js";
import { entry as e_deepgram } from "./deepgram.js";
import { entry as e_discord } from "./discord.js";
import { entry as e_docusign } from "./docusign.js";
import { entry as e_elevenlabs } from "./elevenlabs.js";
import { entry as e_github } from "./github.js";
import { entry as e_gitlab } from "./gitlab.js";
import { entry as e_hubspot } from "./hubspot.js";
import { entry as e_intercom } from "./intercom.js";
import { entry as e_jira } from "./jira.js";
import { entry as e_linear } from "./linear.js";
import { entry as e_monday } from "./monday.js";
import { entry as e_notion } from "./notion.js";
import { entry as e_openai } from "./openai.js";
import { entry as e_paddlebilling } from "./paddlebilling.js";
import { entry as e_paddleclassic } from "./paddleclassic.js";
import { entry as e_pagerduty } from "./pagerduty.js";
import { entry as e_paypal } from "./paypal.js";
import { entry as e_pipedrive } from "./pipedrive.js";
import { entry as e_plaid } from "./plaid.js";
import { entry as e_postmark } from "./postmark.js";
import { entry as e_recall_ai } from "./recall-ai.js";
import { entry as e_replicate } from "./replicate.js";
import { entry as e_resend } from "./resend.js";
import { entry as e_retell } from "./retell.js";
import { entry as e_sendgrid } from "./sendgrid.js";
import { entry as e_sentry } from "./sentry.js";
import { entry as e_shopify } from "./shopify.js";
import { entry as e_slack } from "./slack.js";
import { entry as e_square } from "./square.js";
import { entry as e_stripe } from "./stripe.js";
import { entry as e_supabase } from "./supabase.js";
import { entry as e_telegram } from "./telegram.js";
import { entry as e_twilio } from "./twilio.js";
import { entry as e_typeform } from "./typeform.js";
import { entry as e_vapi } from "./vapi.js";
import { entry as e_vercel } from "./vercel.js";
import { entry as e_whatsapp } from "./whatsapp.js";
import { entry as e_woocommerce } from "./woocommerce.js";
import { entry as e_workos } from "./workos.js";
import { entry as e_zendesk } from "./zendesk.js";
import { entry as e_zoom } from "./zoom.js";

export const registryEntries: ProviderRegistryEntry[] = [
  e_adyen,
  e_anthropic,
  e_assemblyai,
  e_attio,
  e_auth0,
  e_bigcommerce,
  e_bitbucket,
  e_brex,
  e_cal_com,
  e_calendly,
  e_checkout,
  e_clerk,
  e_close_crm,
  e_commercelayer,
  e_deepgram,
  e_discord,
  e_docusign,
  e_elevenlabs,
  e_github,
  e_gitlab,
  e_hubspot,
  e_intercom,
  e_jira,
  e_linear,
  e_monday,
  e_notion,
  e_openai,
  e_paddlebilling,
  e_paddleclassic,
  e_pagerduty,
  e_paypal,
  e_pipedrive,
  e_plaid,
  e_postmark,
  e_recall_ai,
  e_replicate,
  e_resend,
  e_retell,
  e_sendgrid,
  e_sentry,
  e_shopify,
  e_slack,
  e_square,
  e_stripe,
  e_supabase,
  e_telegram,
  e_twilio,
  e_typeform,
  e_vapi,
  e_vercel,
  e_whatsapp,
  e_woocommerce,
  e_workos,
  e_zendesk,
  e_zoom,
];

export const registry: Record<string, ProviderRegistryEntry> = Object.fromEntries(
  registryEntries.map((e) => [e.id, e])
);

export function getProvider(id: string): ProviderRegistryEntry | undefined {
  return registry[id];
}
