name: 📚 Docs Checks

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 📦 Cache npm
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.npm
          key: |
            ${{ runner.os }}-mintlify
          restore-keys: |
            ${{ runner.os }}-mintlify

      - name: 🔗 Check for broken links
        run: npx mintlify@4.0.393 broken-links
