name: "🧪 E2E Tests: Webapp"

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  e2eTests:
    name: "🧪 E2E Tests: Webapp"
    runs-on: warp-ubuntu-latest-x64-16x
    timeout-minutes: 20
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: 🔧 Disable IPv6
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      - name: 🔧 Configure docker address pool
        run: |
          CONFIG='{
            "default-address-pools" : [
              {
                "base" : "172.17.0.0/12",
                "size" : 20
              },
              {
                "base" : "192.168.0.0/16",
                "size" : 24
              }
            ]
          }'
          mkdir -p /etc/docker
          echo "$CONFIG" | sudo tee /etc/docker/daemon.json

      - name: 🔧 Restart docker daemon
        run: sudo systemctl restart docker

      - name: ⬇️ Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10.33.2

      - name: ⎔ Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0
          cache: "pnpm"

      # ..to avoid rate limits when pulling images
      - name: 🐳 Login to DockerHub
        if: ${{ env.DOCKERHUB_USERNAME }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🐳 Skipping DockerHub login (no secrets available)
        if: ${{ !env.DOCKERHUB_USERNAME }}
        run: echo "DockerHub login skipped because secrets are not available."

      - name: 🐳 Pre-pull testcontainer images
        if: ${{ env.DOCKERHUB_USERNAME }}
        run: |
          echo "Pre-pulling Docker images with authenticated session..."
          docker pull postgres:14
          docker pull redis:7.2
          docker pull testcontainers/ryuk:0.11.0
          echo "Image pre-pull complete"

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile

      - name: 📀 Generate Prisma Client
        run: pnpm run generate

      - name: 🏗️ Build Webapp
        run: pnpm run build --filter webapp

      - name: 🧪 Run Webapp E2E Tests
        run: cd apps/webapp && pnpm exec vitest run --config vitest.e2e.config.ts --reporter=default
        env:
          WEBAPP_TEST_VERBOSE: "1"
