name: 🤖 PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"
      - ".changeset/**"
      - "hosting/**"
      - ".github/workflows/helm-prerelease.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  typecheck:
    uses: ./.github/workflows/typecheck.yml

  units:
    uses: ./.github/workflows/unit-tests.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  e2e:
    uses: ./.github/workflows/e2e.yml
    with:
      package: cli-v3

  sdk-compat:
    uses: ./.github/workflows/sdk-compat.yml
