name: Vouch - Check PR

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: mitchellh/vouch/action/check-pr@c6d80ead49839655b61b422700b7a3bc9d0804a9 # v1.4.2
        with:
          pr-number: ${{ github.event.pull_request.number }}
          auto-close: true
          require-vouch: true
        env:
          GH_TOKEN: ${{ github.token }}
