import { type SampleRecord } from "../sampleRecord.js";

/**
 * Auth0 log stream samples. Auth0 authenticates these deliveries with a static bearer token (the
 * Authorization Token set on the log stream), not an HMAC/Ed25519 signature, so no preset applies.
 * Each delivery is a JSON array of log events; every element wraps the actual log fields under `data`,
 * with `data.type` carrying the Auth0 log event type code (see the Log Event Type Codes reference).
 */
export const samples: SampleRecord[] = [
  {
    provider: "auth0",
    providerLabel: "Auth0",
    eventType: "s",
    name: "Successful login",
    description: "A user successfully authenticated against a database connection.",
    body: [
      {
        log_id: "90020250708141238000000000000000001",
        data: {
          date: "2026-07-08T14:12:38.123Z",
          type: "s",
          description: "",
          connection: "Username-Password-Authentication",
          connection_id: "con_9f1KcxcOAJVzAKGh",
          client_id: "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
          client_name: "Trigger.dev Dashboard",
          ip: "203.0.113.42",
          user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
          is_mobile: false,
          hostname: "trigger-dev.us.auth0.com",
          tenant_name: "trigger-dev",
          environment_name: "production",
          strategy: "auth0",
          strategy_type: "database",
          user_id: "auth0|64f1b2e3c9d4a10012345678",
          user_name: "jordan@example.com",
          log_id: "90020250708141238000000000000000001",
          details: {
            initiatedAt: 1752070357800,
            completedAt: 1752070358123,
            elapsedTime: 323,
            session_id: "sess_2yQ8pXwK9nR3vT7hLmZ4jC1s",
          },
        },
      },
    ],
    docsUrl: "https://auth0.com/docs/customize/log-streams/custom-log-streams",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "auth0",
    providerLabel: "Auth0",
    eventType: "fp",
    name: "Failed login (wrong password)",
    description: "A login attempt failed because the password did not match the account.",
    body: [
      {
        log_id: "90020250708141902000000000000000002",
        data: {
          date: "2026-07-08T14:19:02.881Z",
          type: "fp",
          description: "Wrong password.",
          connection: "Username-Password-Authentication",
          connection_id: "con_9f1KcxcOAJVzAKGh",
          client_id: "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
          client_name: "Trigger.dev Dashboard",
          ip: "198.51.100.17",
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          is_mobile: false,
          hostname: "trigger-dev.us.auth0.com",
          tenant_name: "trigger-dev",
          environment_name: "production",
          strategy: "auth0",
          strategy_type: "database",
          user_id: "auth0|64f1b2e3c9d4a10012345678",
          user_name: "jordan@example.com",
          log_id: "90020250708141902000000000000000002",
          details: {
            error: {
              message: "Wrong password.",
              oauthError: "invalid_user_password",
              type: "invalid_password",
            },
          },
        },
      },
    ],
    docsUrl: "https://auth0.com/docs/customize/log-streams/custom-log-streams",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "auth0",
    providerLabel: "Auth0",
    eventType: "fu",
    name: "Failed login (invalid username)",
    description: "A login attempt failed because no account matched the given identifier.",
    body: [
      {
        log_id: "90020250708142511000000000000000003",
        data: {
          date: "2026-07-08T14:25:11.402Z",
          type: "fu",
          description: "Invalid username or password.",
          connection: "Username-Password-Authentication",
          connection_id: "con_9f1KcxcOAJVzAKGh",
          client_id: "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
          client_name: "Trigger.dev Dashboard",
          ip: "203.0.113.90",
          user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15",
          is_mobile: true,
          hostname: "trigger-dev.us.auth0.com",
          tenant_name: "trigger-dev",
          environment_name: "production",
          strategy: "auth0",
          strategy_type: "database",
          user_id: null,
          user_name: "unknown-visitor@example.com",
          log_id: "90020250708142511000000000000000003",
          details: {
            error: {
              message: "Invalid username or password.",
              oauthError: "invalid_user_password",
              type: "invalid_username",
            },
          },
        },
      },
    ],
    docsUrl: "https://auth0.com/docs/customize/log-streams/custom-log-streams",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "auth0",
    providerLabel: "Auth0",
    eventType: "f",
    name: "Failed login (federated connection denied)",
    description:
      "A login attempt failed for a reason outside of bad credentials, e.g. a Post-Login Action denying access on a social connection.",
    body: [
      {
        log_id: "90020250708150044000000000000000004",
        data: {
          date: "2026-07-08T15:00:44.219Z",
          type: "f",
          description: "Access denied.",
          connection: "google-oauth2",
          connection_id: "con_7bWmQdRk2LpNxVaU",
          client_id: "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
          client_name: "Trigger.dev Dashboard",
          ip: "203.0.113.211",
          user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
          is_mobile: false,
          hostname: "trigger-dev.us.auth0.com",
          tenant_name: "trigger-dev",
          environment_name: "production",
          strategy: "google-oauth2",
          strategy_type: "social",
          user_id: "google-oauth2|108234567890123456789",
          user_name: "morgan@example.com",
          log_id: "90020250708150044000000000000000004",
          details: {
            error: {
              message: "Access denied.",
              oauthError: "access_denied",
              type: "oauth-authorization-code",
            },
          },
        },
      },
    ],
    docsUrl: "https://auth0.com/docs/customize/log-streams/custom-log-streams",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "auth0",
    providerLabel: "Auth0",
    eventType: "ss",
    name: "Successful signup",
    description: "A new user completed signup against a database connection.",
    body: [
      {
        log_id: "90020250708153327000000000000000005",
        data: {
          date: "2026-07-08T15:33:27.556Z",
          type: "ss",
          description: "",
          connection: "Username-Password-Authentication",
          connection_id: "con_9f1KcxcOAJVzAKGh",
          client_id: "AaiyAPdpYdesoKnqjj8HJqRn4T5titww",
          client_name: "Trigger.dev Dashboard",
          ip: "203.0.113.55",
          user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
          is_mobile: false,
          hostname: "trigger-dev.us.auth0.com",
          tenant_name: "trigger-dev",
          environment_name: "production",
          strategy: "auth0",
          strategy_type: "database",
          user_id: "auth0|64f1c9a7d8e2b30012349999",
          user_name: "taylor@example.com",
          log_id: "90020250708153327000000000000000005",
          details: {
            initiatedAt: 1752075206900,
            completedAt: 1752075207556,
            elapsedTime: 656,
            session_id: "sess_8kR2wLpN4vT9jC1hZmQ3yX7s",
          },
        },
      },
    ],
    docsUrl: "https://auth0.com/docs/customize/log-streams/custom-log-streams",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
