import { type SampleRecord } from "../sampleRecord.js";

/**
 * Calendly samples. No preset: Calendly signs with its own `Calendly-Webhook-Signature` header
 * (`t=<ts>,v1=<hex>`, HMAC-SHA256 over `{t}.{rawBody}`), which does not match `stripe-signature`.
 */
export const samples: SampleRecord[] = [
  {
    provider: "calendly",
    providerLabel: "Calendly",
    eventType: "invitee.created",
    name: "Invitee created (one-on-one)",
    description: "A new invitee booked a one-on-one event, with a custom question answered.",
    body: {
      created_at: "2026-06-01T15:22:41.000000Z",
      event: "invitee.created",
      payload: {
        cancel_url: "https://calendly.com/cancellations/3f6a1c2e-71b4-4b8d-9e2a-6d4f0a8b1c3d",
        created_at: "2026-06-01T15:22:41.000000Z",
        email: "jordan.rivera@example.com",
        event: "https://api.calendly.com/scheduled_events/8f2b6c1a-9d3e-4a7f-b5c2-1e6f9a0d4b7c",
        name: "Jordan Rivera",
        new_invitee: null,
        old_invitee: null,
        questions_and_answers: [
          {
            question: "What would you like to discuss?",
            answer: "Onboarding walkthrough for the new workspace.",
            position: 0,
          },
        ],
        reschedule_url: "https://calendly.com/reschedulings/3f6a1c2e-71b4-4b8d-9e2a-6d4f0a8b1c3d",
        rescheduled: false,
        status: "active",
        text_reminder_number: null,
        timezone: "America/Los_Angeles",
        tracking: {
          utm_campaign: null,
          utm_source: null,
          utm_medium: null,
          utm_content: null,
          utm_term: null,
          salesforce_uuid: null,
        },
        updated_at: "2026-06-01T15:22:41.000000Z",
        uri: "https://api.calendly.com/scheduled_events/8f2b6c1a-9d3e-4a7f-b5c2-1e6f9a0d4b7c/invitees/1a4d7e2b-5c8f-4a1d-9b3e-6f0c8d2a5b7e",
      },
    },
    docsUrl: "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "calendly",
    providerLabel: "Calendly",
    eventType: "invitee.created",
    name: "Invitee created (group event, via campaign link)",
    description: "A new invitee joined a group event through a link carrying UTM tracking params.",
    body: {
      created_at: "2026-06-03T09:05:12.000000Z",
      event: "invitee.created",
      payload: {
        cancel_url: "https://calendly.com/cancellations/9a1e5f3c-2b7d-4c6a-8e1f-0d3b6a9c2e5f",
        created_at: "2026-06-03T09:05:12.000000Z",
        email: "priya.nair@example.com",
        event: "https://api.calendly.com/scheduled_events/2c5e8a1d-4f7b-4d9e-a2c5-8b1e4f7a0d3c",
        name: "Priya Nair",
        new_invitee: null,
        old_invitee: null,
        questions_and_answers: [],
        reschedule_url: "https://calendly.com/reschedulings/9a1e5f3c-2b7d-4c6a-8e1f-0d3b6a9c2e5f",
        rescheduled: false,
        status: "active",
        text_reminder_number: null,
        timezone: "Europe/London",
        tracking: {
          utm_campaign: "summer-webinar",
          utm_source: "newsletter",
          utm_medium: "email",
          utm_content: "cta-button",
          utm_term: null,
          salesforce_uuid: null,
        },
        updated_at: "2026-06-03T09:05:12.000000Z",
        uri: "https://api.calendly.com/scheduled_events/2c5e8a1d-4f7b-4d9e-a2c5-8b1e4f7a0d3c/invitees/6d9c2a5e-7f1b-4a3d-9e6c-2b5f8a1d4c7e",
      },
    },
    docsUrl: "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "calendly",
    providerLabel: "Calendly",
    eventType: "invitee.created",
    name: "Invitee created (rebooked after reschedule)",
    description:
      "The replacement invitee record created when an existing invitee reschedules; old_invitee links back to the canceled booking.",
    body: {
      created_at: "2026-06-05T18:41:07.000000Z",
      event: "invitee.created",
      payload: {
        cancel_url: "https://calendly.com/cancellations/5b8e1c4a-9f2d-4b6e-8c1a-3d5f9b2e6a8c",
        created_at: "2026-06-05T18:41:07.000000Z",
        email: "morgan.blake@example.com",
        event: "https://api.calendly.com/scheduled_events/4d7f0a3c-6b9e-4c2d-8f5a-1e3d6b9c2f5a",
        name: "Morgan Blake",
        new_invitee: null,
        old_invitee:
          "https://api.calendly.com/scheduled_events/9e2c5a8d-1f4b-4d7e-a3c6-5b8e1a4d7c9e/invitees/3c6f9a2d-5e8b-4a1c-9d3f-6a9c2e5b8d1f",
        questions_and_answers: [
          {
            question: "Anything else we should know?",
            answer: "Moving the call an hour later.",
            position: 0,
          },
        ],
        reschedule_url: "https://calendly.com/reschedulings/5b8e1c4a-9f2d-4b6e-8c1a-3d5f9b2e6a8c",
        rescheduled: false,
        status: "active",
        text_reminder_number: null,
        timezone: "America/New_York",
        tracking: {
          utm_campaign: null,
          utm_source: null,
          utm_medium: null,
          utm_content: null,
          utm_term: null,
          salesforce_uuid: null,
        },
        updated_at: "2026-06-05T18:41:07.000000Z",
        uri: "https://api.calendly.com/scheduled_events/4d7f0a3c-6b9e-4c2d-8f5a-1e3d6b9c2f5a/invitees/8f1a4d7c-2e5b-4a9d-8c1f-3e6a9d2c5f8b",
      },
    },
    docsUrl: "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "calendly",
    providerLabel: "Calendly",
    eventType: "invitee.canceled",
    name: "Invitee canceled (self-canceled with reason)",
    description: "The invitee canceled their own booking and left a cancellation reason.",
    body: {
      created_at: "2026-06-08T11:30:55.000000Z",
      event: "invitee.canceled",
      payload: {
        cancel_url: "https://calendly.com/cancellations/3f6a1c2e-71b4-4b8d-9e2a-6d4f0a8b1c3d",
        cancellation: {
          canceled_by: "Jordan Rivera",
          canceler_type: "invitee",
          reason: "Something came up, will rebook next week.",
        },
        created_at: "2026-06-01T15:22:41.000000Z",
        email: "jordan.rivera@example.com",
        event: "https://api.calendly.com/scheduled_events/8f2b6c1a-9d3e-4a7f-b5c2-1e6f9a0d4b7c",
        name: "Jordan Rivera",
        new_invitee: null,
        old_invitee: null,
        questions_and_answers: [
          {
            question: "What would you like to discuss?",
            answer: "Onboarding walkthrough for the new workspace.",
            position: 0,
          },
        ],
        reschedule_url: "https://calendly.com/reschedulings/3f6a1c2e-71b4-4b8d-9e2a-6d4f0a8b1c3d",
        rescheduled: false,
        status: "canceled",
        text_reminder_number: null,
        timezone: "America/Los_Angeles",
        tracking: {
          utm_campaign: null,
          utm_source: null,
          utm_medium: null,
          utm_content: null,
          utm_term: null,
          salesforce_uuid: null,
        },
        updated_at: "2026-06-08T11:30:55.000000Z",
        uri: "https://api.calendly.com/scheduled_events/8f2b6c1a-9d3e-4a7f-b5c2-1e6f9a0d4b7c/invitees/1a4d7e2b-5c8f-4a1d-9b3e-6f0c8d2a5b7e",
      },
    },
    docsUrl: "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "calendly",
    providerLabel: "Calendly",
    eventType: "invitee.canceled",
    name: "Invitee canceled (host rescheduled the meeting)",
    description:
      "The host rescheduled the meeting on the invitee's behalf; rescheduled is true and new_invitee points at the replacement booking.",
    body: {
      created_at: "2026-06-05T18:41:07.000000Z",
      event: "invitee.canceled",
      payload: {
        cancel_url: "https://calendly.com/cancellations/9e2c5a8d-1f4b-4d7e-a3c6-5b8e1a4d7c9e",
        cancellation: {
          canceled_by: "Alex Chen",
          canceler_type: "host",
          reason: null,
        },
        created_at: "2026-06-02T13:00:00.000000Z",
        email: "morgan.blake@example.com",
        event: "https://api.calendly.com/scheduled_events/9e2c5a8d-1f4b-4d7e-a3c6-5b8e1a4d7c9e",
        name: "Morgan Blake",
        new_invitee:
          "https://api.calendly.com/scheduled_events/4d7f0a3c-6b9e-4c2d-8f5a-1e3d6b9c2f5a/invitees/8f1a4d7c-2e5b-4a9d-8c1f-3e6a9d2c5f8b",
        old_invitee: null,
        questions_and_answers: [
          {
            question: "Anything else we should know?",
            answer: "Moving the call an hour later.",
            position: 0,
          },
        ],
        reschedule_url: "https://calendly.com/reschedulings/9e2c5a8d-1f4b-4d7e-a3c6-5b8e1a4d7c9e",
        rescheduled: true,
        status: "canceled",
        text_reminder_number: null,
        timezone: "America/New_York",
        tracking: {
          utm_campaign: null,
          utm_source: null,
          utm_medium: null,
          utm_content: null,
          utm_term: null,
          salesforce_uuid: null,
        },
        updated_at: "2026-06-05T18:41:07.000000Z",
        uri: "https://api.calendly.com/scheduled_events/9e2c5a8d-1f4b-4d7e-a3c6-5b8e1a4d7c9e/invitees/3c6f9a2d-5e8b-4a1c-9d3f-6a9c2e5b8d1f",
      },
    },
    docsUrl: "https://developer.calendly.com/api-docs/4c305798a61d3-webhook-signatures",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
