import { type SampleRecord } from "../sampleRecord.js";

/**
 * Close samples. Every delivery wraps a single Event Log entry in `{ event, subscription_id }`;
 * `event.object_type` + `event.action` together identify the resource and action (Close's own docs
 * list them as separate fields, e.g. `lead` / `created`), so `eventType` here joins them as
 * `"<object_type>.<action>"`. Close does not sign with any of our verifier presets (see the registry
 * entry), so no sample sets `presetId`. The `lead.created` and `activity.*.created` bodies follow the
 * Lead / Contact / CallActivity field names from the Close API reference; the opportunity-status-change
 * activity's `old_status` / `new_status` fields are inferred from the Event Log docs' description of
 * that activity type (the reference page for that resource ships no field-level schema). The final
 * sample is Close's own published webhook example (an opportunity moving to "Won"), lightly
 * re-dated.
 */
export const samples: SampleRecord[] = [
  {
    provider: "close-crm",
    providerLabel: "Close",
    eventType: "lead.created",
    name: "Lead created",
    description: "A new lead was created in the organization, regardless of the method used.",
    body: {
      event: {
        id: "ev_2r8KzQyF7bWmNdE1TxJcP4",
        date_created: "2026-07-10T15:02:11.204000",
        date_updated: "2026-07-10T15:02:11.204000",
        object_type: "lead",
        object_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
        lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
        organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
        user_id: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
        request_id: "req_7YtRj2AmVp3Km9RtWzY6Qa",
        action: "created",
        changed_fields: [],
        previous_data: null,
        data: {
          id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
          name: "Acme Rocket Co",
          display_name: "Acme Rocket Co",
          description: "Inbound demo request from the pricing page.",
          url: "https://acmerocket.example",
          status_id: "stat_1Nc4Bf7Hn4Wq7VtRj2AmY8",
          status_label: "Potential",
          html_url: "https://app.close.com/lead/lead_9k2R7wYtVbXmS3Ac6Fq1Zp/",
          addresses: [
            {
              label: "business",
              address_1: "142 Harbor Ave",
              address_2: "Suite 400",
              city: "Portland",
              state: "OR",
              zipcode: "97201",
              country: "US",
            },
          ],
          contacts: [
            {
              id: "cont_Bf7Hn4Wq7VtRj2AmY8bKzX",
              name: "Dana Whitfield",
              title: "VP Operations",
              display_name: "Dana Whitfield",
              emails: [
                { email: "dana@acmerocket.example", type: "office", is_unsubscribed: false },
              ],
              phones: [
                {
                  phone: "+15035550142",
                  type: "office",
                  phone_formatted: "+1 503-555-0142",
                  country: "US",
                },
              ],
              lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
              organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
            },
          ],
          custom: {},
          created_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          created_by_name: "Sam Okafor",
          updated_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
          date_created: "2026-07-10T15:02:11.198000+00:00",
          date_updated: "2026-07-10T15:02:11.198000+00:00",
        },
        meta: { request_method: "POST", request_path: "/api/v1/lead/" },
      },
      subscription_id: "whsub_Km9RtWzY6QaX1Nc4Bf7Hn4",
    },
    docsUrl: "https://developer.close.com/topics/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "close-crm",
    providerLabel: "Close",
    eventType: "activity.note.created",
    name: "Note activity created",
    description: "A freeform note was logged on a lead.",
    body: {
      event: {
        id: "ev_4TxJcP4r8KzQyF7bWmNdE1",
        date_created: "2026-07-10T15:11:47.512000",
        date_updated: "2026-07-10T15:11:47.512000",
        object_type: "activity.note",
        object_id: "acti_Wq7VtRj2AmY8bKzXc1SHn4",
        lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
        organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
        user_id: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
        request_id: "req_9RtWzY6QaX1Nc4Bf7Hn4Wq",
        action: "created",
        changed_fields: [],
        previous_data: null,
        data: {
          id: "acti_Wq7VtRj2AmY8bKzXc1SHn4",
          _type: "Note",
          note: "Left a voicemail, asked to follow up next week after their board meeting.",
          note_html:
            "<p>Left a voicemail, asked to follow up next week after their board meeting.</p>",
          lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
          contact_id: "cont_Bf7Hn4Wq7VtRj2AmY8bKzX",
          organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
          created_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          created_by_name: "Sam Okafor",
          updated_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          date_created: "2026-07-10T15:11:47.502000+00:00",
          date_updated: "2026-07-10T15:11:47.502000+00:00",
        },
        meta: { request_method: "POST", request_path: "/api/v1/activity/note/" },
      },
      subscription_id: "whsub_Km9RtWzY6QaX1Nc4Bf7Hn4",
    },
    docsUrl: "https://developer.close.com/api/resources/activities/notes.md",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "close-crm",
    providerLabel: "Close",
    eventType: "activity.call.created",
    name: "Call activity created",
    description: "An inbound call was logged on a lead's contact.",
    body: {
      event: {
        id: "ev_7bWmNdE1TxJcP4r8KzQyF4",
        date_created: "2026-07-10T16:04:33.877000",
        date_updated: "2026-07-10T16:04:33.877000",
        object_type: "activity.call",
        object_id: "acti_c1SHn4Wq7VtRj2AmY8bKzX",
        lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
        organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
        user_id: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
        request_id: "req_1Nc4Bf7Hn4Wq7VtRj2AmY8",
        action: "created",
        changed_fields: [],
        previous_data: null,
        data: {
          id: "acti_c1SHn4Wq7VtRj2AmY8bKzX",
          _type: "Call",
          direction: "inbound",
          status: "completed",
          duration: 184,
          phone: "+15035550142",
          note: "",
          recording_url: null,
          outcome_id: null,
          contact_id: "cont_Bf7Hn4Wq7VtRj2AmY8bKzX",
          lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
          organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
          created_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          created_by_name: "Sam Okafor",
          date_created: "2026-07-10T16:04:33.861000+00:00",
          date_updated: "2026-07-10T16:04:33.861000+00:00",
        },
        meta: { request_method: "POST", request_path: "/api/v1/activity/call/" },
      },
      subscription_id: "whsub_Km9RtWzY6QaX1Nc4Bf7Hn4",
    },
    docsUrl: "https://developer.close.com/api/resources/activities/calls.md",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "close-crm",
    providerLabel: "Close",
    eventType: "activity.opportunity_status_change.created",
    name: "Opportunity status change activity created",
    description:
      "A dedicated status-change activity was created for an opportunity (distinct from the opportunity's own `updated` event); `new_status`/`old_status` name the transition.",
    body: {
      event: {
        id: "ev_Bf7Hn4Wq7VtRj2AmY8bKzX",
        date_created: "2026-07-10T17:20:05.339000",
        date_updated: "2026-07-10T17:20:05.339000",
        object_type: "activity.opportunity_status_change",
        object_id: "acti_5R3RfhIQixdnmjf2wMS9M6",
        lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
        organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
        user_id: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
        request_id: "req_c1SHn4Wq7VtRj2AmY8bKzXc",
        action: "created",
        changed_fields: [],
        previous_data: null,
        data: {
          id: "acti_5R3RfhIQixdnmjf2wMS9M6",
          _type: "StatusChange.Opportunity",
          opportunity_id: "oppo_8H4sjNso7FyBFaeR3RXi5P",
          lead_id: "lead_9k2R7wYtVbXmS3Ac6Fq1Zp",
          old_status: { id: "stat_3FD9DnGUCJzccBKTh8LiiK", label: "Active", type: "active" },
          new_status: { id: "stat_wMS9M6HC2O3CSEOzF5g2vE", label: "Won", type: "won" },
          organization_id: "orga_Hn4Wq7VtRj2AmY8bKzXc1S",
          created_by: "user_Vp3Km9RtWzY6QaX1Nc4Bf7",
          created_by_name: "Sam Okafor",
          date_created: "2026-07-10T17:20:05.331000+00:00",
          date_updated: "2026-07-10T17:20:05.331000+00:00",
        },
        meta: {
          request_method: "PUT",
          request_path: "/api/v1/opportunity/oppo_8H4sjNso7FyBFaeR3RXi5P/",
        },
      },
      subscription_id: "whsub_Km9RtWzY6QaX1Nc4Bf7Hn4",
    },
    docsUrl: "https://developer.close.com/api/resources/activities/opportunity-status-changes.md",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "close-crm",
    providerLabel: "Close",
    eventType: "opportunity.updated",
    name: "Opportunity updated (won)",
    description:
      "Close's own published webhook example: an opportunity's status field changed to \"Won\"; `previous_data` carries the prior status. Re-dated from the docs example, otherwise verbatim.",
    body: {
      event: {
        id: "ev_2sYKRjcrA79yKxi3S4Crd7",
        date_created: "2026-07-10T18:48:23.395000",
        date_updated: "2026-07-10T18:48:23.395000",
        object_type: "opportunity",
        object_id: "oppo_7H4sjNso7FyBFaeR3RXi5PMJbilfo0c6UPCxsJtEhCO",
        lead_id: "lead_zwqYhEFwzPyfCErS8uQ77is2wFLvr9BgVi6cTfbFM68",
        organization_id: "orga_XbVPx5fFbKlYTz9PW5Ih1XDhViV10YihIaEgMEb6fVW",
        user_id: "user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA",
        request_id: "req_4S2L8JTBAA1OUS74SVmfbN",
        action: "updated",
        changed_fields: ["confidence", "date_updated", "status_id", "status_label", "status_type"],
        previous_data: {
          status_type: "active",
          confidence: 70,
          date_updated: "2026-07-10T18:47:39.873000+00:00",
          status_id: "stat_3FD9DnGUCJzccBKTh8LiiKoyVPpMJsOkJdcGoA5AYKH",
          status_label: "Active",
        },
        data: {
          id: "oppo_8H4sjNso7FyBFaeR3RXi5PMJbilfo0c6UPCxsJtEhCO",
          lead_id: "lead_zwqYhEFwzPyfCErS8uQ77is2wFLvr9BgVi6cTfbFM68",
          lead_name: "KLine",
          contact_id: "cont_BwlwYQkIP6AooiXP1CMvc6Zbb5gGh2gPu4dqIDlDrII",
          contact_name: "Mr. Jones",
          organization_id: "orga_XbVPx5fFbKlYTz9PW5Ih1XDhViV10YihIaEgMEb6fVW",
          status_id: "stat_wMS9M6HC2O3CSEOzF5g2vEGt6RM5R3RfhIQixdnmjf2",
          status_label: "Won",
          status_type: "won",
          confidence: 100,
          value: 100000,
          value_period: "one_time",
          value_currency: "USD",
          value_formatted: "$1,000",
          note: "",
          date_won: "2026-07-10",
          date_lost: null,
          created_by: "user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA",
          created_by_name: "Joe Kemp",
          updated_by: "user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA",
          updated_by_name: "Joe Kemp",
          user_id: "user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA",
          user_name: "Joe Kemp",
          date_created: "2026-07-10T18:41:24.496000+00:00",
          date_updated: "2026-07-10T18:48:23.392000+00:00",
        },
        meta: {
          request_method: "PUT",
          request_path: "/api/v1/opportunity/oppo_7H4sjNso7FyBFaeR3RXi5PMJbilfo0c6UPCxsJtEhCO/",
        },
      },
      subscription_id: "whsub_8AmjKCZYT3zI8eZoi4HhFC",
    },
    docsUrl: "https://developer.close.com/topics/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
