import { type SampleRecord } from "../sampleRecord.js";

/**
 * GitLab's default webhook auth is a plaintext `X-Gitlab-Token` shared secret (no signature at all),
 * which our hookdeck-sourced samples carry via extraHeaders and which does not map to any preset.
 * GitLab also offers an opt-in "signing token" mode that follows the Standard Webhooks spec exactly:
 * `webhook-id` / `webhook-timestamp` / `webhook-signature` headers, HMAC-SHA256 base64 over
 * `{id}.{timestamp}.{body}`, secret prefixed `whsec_`. That mode matches our `svix` preset, so these
 * samples are tagged `presetId: "svix"` and cover event types not already present in the hookdeck set
 * (Merge Request Hook, Pipeline Hook, Job Hook).
 */
export const samples: SampleRecord[] = [
  {
    provider: "gitlab",
    providerLabel: "GitLab",
    presetId: "svix",
    eventType: "Merge Request Hook",
    name: "Merge request opened",
    description: "A merge request is opened against the target branch.",
    body: {
      object_kind: "merge_request",
      event_type: "merge_request",
      user: {
        id: 1,
        name: "Alex Garcia",
        username: "agarcia",
        avatar_url: "https://www.gravatar.com/avatar/1a29da0ccd0994?s=80&d=identicon",
        email: "agarcia@example.com",
      },
      project: {
        id: 2,
        name: "Flight Management",
        description: "Flight management application for tracking aircraft status.",
        web_url: "https://gitlab.example.com/flightjs/flight-management",
        avatar_url: null,
        git_ssh_url: "ssh://git@gitlab.example.com/flightjs/flight-management.git",
        git_http_url: "https://gitlab.example.com/flightjs/flight-management.git",
        namespace: "Flightjs",
        visibility_level: 0,
        path_with_namespace: "flightjs/flight-management",
        default_branch: "main",
        ci_config_path: null,
      },
      object_attributes: {
        id: 93,
        iid: 16,
        author_id: 1,
        created_at: "2026-06-30 05:56:22 UTC",
        updated_at: "2026-06-30 05:56:25 UTC",
        title: "Add input validation to booking form",
        description: "This merge request adds input validation to the booking form.",
        draft: false,
        state: "opened",
        merge_status: "checking",
        detailed_merge_status: "checking",
        source_branch: "feature/booking-validation",
        source_project_id: 2,
        target_branch: "main",
        target_project_id: 2,
        target_branch_protected: true,
        merge_commit_sha: null,
        merged_at: null,
        merge_error: null,
        merge_when_pipeline_succeeds: false,
        milestone_id: 8,
        assignee_ids: [1],
        reviewer_ids: [25],
        labels: [{ id: 19, title: "enhancement", color: "#adb21a" }],
        last_commit: {
          id: "e59094b8de0f2f91abbe4760a52d9137260252d8",
          message: "Add email format validation",
          timestamp: "2026-06-30T05:01:10+00:00",
          url: "https://gitlab.example.com/flightjs/flight-management/-/commit/e59094b8de0f2f91abbe4760a52d9137260252d8",
          author: { name: "Alex Garcia", email: "agarcia@example.com" },
        },
        url: "https://gitlab.example.com/flightjs/flight-management/-/merge_requests/16",
        action: "open",
        actioned_at: "2026-06-30 05:56:26 UTC",
      },
      labels: [{ id: 19, title: "enhancement", color: "#adb21a" }],
      changes: {
        merge_status: { previous: "preparing", current: "checking" },
        updated_at: { previous: "2026-06-30 05:56:22 UTC", current: "2026-06-30 05:56:25 UTC" },
      },
      assignees: [
        { id: 1, name: "Alex Garcia", username: "agarcia", email: "agarcia@example.com" },
      ],
      reviewers: [
        {
          id: 25,
          name: "Sidney Jones",
          username: "sjones",
          state: "unreviewed",
          re_requested: false,
        },
      ],
    },
    extraHeaders: {
      "x-gitlab-event": "Merge Request Hook",
      "x-gitlab-instance": "https://gitlab.example.com",
    },
    docsUrl:
      "https://docs.gitlab.com/user/project/integrations/webhook_events/#merge-request-events",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "gitlab",
    providerLabel: "GitLab",
    presetId: "svix",
    eventType: "Pipeline Hook",
    name: "Pipeline succeeded",
    description: "A CI/CD pipeline finishes with an overall success status.",
    body: {
      object_kind: "pipeline",
      object_attributes: {
        id: 31,
        iid: 3,
        name: "Pipeline for branch: main",
        ref: "main",
        tag: false,
        sha: "bcbb5ec396a2c0f828686f14fac9b80b780504f2",
        before_sha: "959e04d7c7a30600b7a35cb4a53db4b0ae0f0433",
        source: "push",
        status: "success",
        detailed_status: "passed",
        stages: ["build", "test", "deploy"],
        created_at: "2026-06-30 15:23:28 UTC",
        finished_at: "2026-06-30 15:26:29 UTC",
        duration: 63,
        queued_duration: 10,
        url: "https://gitlab.example.com/flightjs/flight-management/-/pipelines/31",
      },
      merge_request: null,
      user: {
        id: 1,
        name: "Alex Garcia",
        username: "agarcia",
        avatar_url: "https://www.gravatar.com/avatar/1a29da0ccd0994?s=80&d=identicon",
        email: "agarcia@example.com",
      },
      project: {
        id: 2,
        name: "Flight Management",
        web_url: "https://gitlab.example.com/flightjs/flight-management",
        namespace: "Flightjs",
        visibility_level: 0,
        path_with_namespace: "flightjs/flight-management",
        default_branch: "main",
      },
      commit: {
        id: "bcbb5ec396a2c0f828686f14fac9b80b780504f2",
        message: "Add email format validation\n",
        title: "Add email format validation",
        timestamp: "2026-06-30T15:23:21+00:00",
        url: "https://gitlab.example.com/flightjs/flight-management/-/commit/bcbb5ec396a2c0f828686f14fac9b80b780504f2",
        author: { name: "Alex Garcia", email: "agarcia@example.com" },
      },
      builds: [
        {
          id: 380,
          stage: "deploy",
          name: "production",
          status: "success",
          created_at: "2026-06-30 15:23:28 UTC",
          started_at: "2026-06-30 15:25:40 UTC",
          finished_at: "2026-06-30 15:26:29 UTC",
          duration: 49.0,
          when: "manual",
          manual: true,
          allow_failure: false,
        },
        {
          id: 377,
          stage: "test",
          name: "test-image",
          status: "success",
          created_at: "2026-06-30 15:23:28 UTC",
          started_at: "2026-06-30 15:24:12 UTC",
          finished_at: "2026-06-30 15:24:29 UTC",
          duration: 17.0,
          when: "on_success",
          manual: false,
          allow_failure: false,
        },
      ],
    },
    extraHeaders: {
      "x-gitlab-event": "Pipeline Hook",
      "x-gitlab-instance": "https://gitlab.example.com",
    },
    docsUrl: "https://docs.gitlab.com/user/project/integrations/webhook_events/#pipeline-events",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "gitlab",
    providerLabel: "GitLab",
    presetId: "svix",
    eventType: "Job Hook",
    name: "Job created",
    description: "An individual CI/CD job within a pipeline changes state.",
    body: {
      object_kind: "build",
      ref: "main",
      tag: false,
      before_sha: "2293ada6b400935a1378653304eaf6221e0fdb8f",
      sha: "2293ada6b400935a1378653304eaf6221e0fdb8f",
      retries_count: 0,
      build_id: 1977,
      build_name: "test-image",
      build_stage: "test",
      build_status: "created",
      build_created_at: "2026-06-30T02:41:37.886Z",
      build_started_at: null,
      build_finished_at: null,
      build_duration: null,
      build_allow_failure: false,
      build_failure_reason: "unknown_failure",
      pipeline_id: 2366,
      runner: {
        id: 380987,
        description: "shared-runner-6.gitlab.example.com",
        runner_type: "instance_type",
        active: true,
        is_shared: true,
        tags: ["linux", "docker"],
      },
      project_id: 2,
      project_name: "flightjs/flight-management",
      user: {
        id: 1,
        name: "Alex Garcia",
        username: "agarcia",
        email: "agarcia@example.com",
      },
      commit: {
        id: 2366,
        name: "Build pipeline",
        sha: "2293ada6b400935a1378653304eaf6221e0fdb8f",
        message: "Add email format validation\n",
        author_name: "Alex Garcia",
        author_email: "agarcia@example.com",
        status: "created",
        duration: null,
      },
      repository: {
        name: "flight-management",
        url: "https://gitlab.example.com/flightjs/flight-management",
        git_ssh_url: "ssh://git@gitlab.example.com/flightjs/flight-management.git",
        git_http_url: "https://gitlab.example.com/flightjs/flight-management.git",
        visibility_level: 0,
      },
      project: {
        id: 2,
        name: "Flight Management",
        web_url: "https://gitlab.example.com/flightjs/flight-management",
        namespace: "Flightjs",
        visibility_level: 0,
        path_with_namespace: "flightjs/flight-management",
        default_branch: "main",
      },
      environment: null,
    },
    extraHeaders: {
      "x-gitlab-event": "Job Hook",
      "x-gitlab-instance": "https://gitlab.example.com",
    },
    docsUrl: "https://docs.gitlab.com/user/project/integrations/webhook_events/#job-events",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
