/** GENERATED by catalog/build-aggregates.ts. Do not edit by hand. */
import { type SampleRecord } from "../sampleRecord.js";
import { samples as s_anthropic } from "./anthropic.js";
import { samples as s_assemblyai } from "./assemblyai.js";
import { samples as s_attio } from "./attio.js";
import { samples as s_auth0 } from "./auth0.js";
import { samples as s_brex } from "./brex.js";
import { samples as s_cal_com } from "./cal-com.js";
import { samples as s_calendly } from "./calendly.js";
import { samples as s_clerk } from "./clerk.js";
import { samples as s_close_crm } from "./close-crm.js";
import { samples as s_deepgram } from "./deepgram.js";
import { samples as s_discord } from "./discord.js";
import { samples as s_docusign } from "./docusign.js";
import { samples as s_elevenlabs } from "./elevenlabs.js";
import { samples as s_gitlab } from "./gitlab.js";
import { samples as s_intercom } from "./intercom.js";
import { samples as s_jira } from "./jira.js";
import { samples as s_linear } from "./linear.js";
import { samples as s_notion } from "./notion.js";
import { samples as s_openai } from "./openai.js";
import { samples as s_pagerduty } from "./pagerduty.js";
import { samples as s_plaid } from "./plaid.js";
import { samples as s_postmark } from "./postmark.js";
import { samples as s_recall_ai } from "./recall-ai.js";
import { samples as s_replicate } from "./replicate.js";
import { samples as s_resend } from "./resend.js";
import { samples as s_retell } from "./retell.js";
import { samples as s_sendgrid } from "./sendgrid.js";
import { samples as s_sentry } from "./sentry.js";
import { samples as s_slack } from "./slack.js";
import { samples as s_square } from "./square.js";
import { samples as s_supabase } from "./supabase.js";
import { samples as s_telegram } from "./telegram.js";
import { samples as s_twilio } from "./twilio.js";
import { samples as s_typeform } from "./typeform.js";
import { samples as s_vapi } from "./vapi.js";
import { samples as s_vercel } from "./vercel.js";
import { samples as s_whatsapp } from "./whatsapp.js";
import { samples as s_workos } from "./workos.js";
import { samples as s_zendesk } from "./zendesk.js";
import { samples as s_zoom } from "./zoom.js";

export const handAuthoredSamples: SampleRecord[] = [
  ...s_anthropic,
  ...s_assemblyai,
  ...s_attio,
  ...s_auth0,
  ...s_brex,
  ...s_cal_com,
  ...s_calendly,
  ...s_clerk,
  ...s_close_crm,
  ...s_deepgram,
  ...s_discord,
  ...s_docusign,
  ...s_elevenlabs,
  ...s_gitlab,
  ...s_intercom,
  ...s_jira,
  ...s_linear,
  ...s_notion,
  ...s_openai,
  ...s_pagerduty,
  ...s_plaid,
  ...s_postmark,
  ...s_recall_ai,
  ...s_replicate,
  ...s_resend,
  ...s_retell,
  ...s_sendgrid,
  ...s_sentry,
  ...s_slack,
  ...s_square,
  ...s_supabase,
  ...s_telegram,
  ...s_twilio,
  ...s_typeform,
  ...s_vapi,
  ...s_vercel,
  ...s_whatsapp,
  ...s_workos,
  ...s_zendesk,
  ...s_zoom,
];
