import { type SampleRecord } from "../sampleRecord.js";

/**
 * Intercom webhook notification samples. Every delivery shares the same envelope
 * (`type: "notification_event"`, `topic`, `app_id`, `delivery_attempts`, `first_sent_at`,
 * `data.item`); `eventType` mirrors `topic`, the real discriminant. No preset applies (Intercom
 * signs with HMAC-SHA1 over `X-Hub-Signature`, not one of our supported schemes), so no
 * `presetId` is set.
 */
export const samples: SampleRecord[] = [
  {
    provider: "intercom",
    providerLabel: "Intercom",
    eventType: "conversation.user.created",
    name: "Conversation created by user",
    description: "A contact started a new conversation from the Messenger.",
    body: {
      type: "notification_event",
      topic: "conversation.user.created",
      id: "notif_5f27a9e0-0e33-4a1e-8f7c-2b6d4a9c11f0",
      app_id: "a86dr8yl",
      created_at: 1781524800,
      delivery_attempts: 1,
      first_sent_at: 1781524800,
      data: {
        item: {
          type: "conversation",
          id: "195208945002873",
          created_at: 1781524800,
          updated_at: 1781524800,
          waiting_since: 1781524800,
          snoozed_until: null,
          source: {
            type: "conversation",
            id: "403982210",
            delivered_as: "customer_initiated",
            subject: "",
            body: "<p>Hi, I'm having trouble connecting my Slack workspace to notifications.</p>",
            author: {
              type: "user",
              id: "6620fa1e8f2b3c4d5e6f7890",
              name: "Priya Desai",
              email: "priya@northwind.example",
            },
            attachments: [],
            url: null,
            redacted: false,
          },
          contacts: {
            type: "contact.list",
            contacts: [{ type: "contact", id: "6620fa1e8f2b3c4d5e6f7890" }],
          },
          teammates: null,
          admin_assignee_id: null,
          team_assignee_id: "5017691",
          open: true,
          state: "open",
          read: false,
          tags: { type: "tag.list", tags: [] },
          priority: "not_priority",
          conversation_rating: null,
          statistics: {
            time_to_assignment: null,
            time_to_admin_reply: null,
            time_to_first_close: null,
            time_to_last_close: null,
            median_time_to_reply: null,
            first_contact_reply_at: 1781524800,
            first_assignment_at: null,
            first_admin_reply_at: null,
            first_close_at: null,
            last_assignment_at: null,
            last_contact_reply_at: 1781524800,
            last_admin_reply_at: null,
            last_close_at: null,
            count_reopens: 0,
            count_assignments: 0,
            count_conversation_parts: 0,
          },
          conversation_parts: {
            type: "conversation_part.list",
            conversation_parts: [],
            total_count: 0,
          },
        },
      },
    },
    docsUrl: "https://developers.intercom.com/docs/references/webhooks/webhook-models",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "intercom",
    providerLabel: "Intercom",
    eventType: "conversation.user.replied",
    name: "User replied to a conversation",
    description: "The contact who opened the conversation sent a follow-up reply.",
    body: {
      type: "notification_event",
      topic: "conversation.user.replied",
      id: "notif_8a41c6d2-4b8e-4f2a-9c3d-7e0f5a8b2d61",
      app_id: "a86dr8yl",
      created_at: 1781528440,
      delivery_attempts: 1,
      first_sent_at: 1781528440,
      data: {
        item: {
          type: "conversation",
          id: "195208945002873",
          created_at: 1781524800,
          updated_at: 1781528440,
          waiting_since: 1781528440,
          snoozed_until: null,
          source: {
            type: "conversation",
            id: "403982210",
            delivered_as: "customer_initiated",
            subject: "",
            body: "<p>Hi, I'm having trouble connecting my Slack workspace to notifications.</p>",
            author: {
              type: "user",
              id: "6620fa1e8f2b3c4d5e6f7890",
              name: "Priya Desai",
              email: "priya@northwind.example",
            },
            attachments: [],
            url: null,
            redacted: false,
          },
          contacts: {
            type: "contact.list",
            contacts: [{ type: "contact", id: "6620fa1e8f2b3c4d5e6f7890" }],
          },
          teammates: null,
          admin_assignee_id: null,
          team_assignee_id: "5017691",
          open: true,
          state: "open",
          read: false,
          tags: { type: "tag.list", tags: [] },
          priority: "not_priority",
          conversation_rating: null,
          statistics: {
            time_to_assignment: null,
            time_to_admin_reply: null,
            time_to_first_close: null,
            time_to_last_close: null,
            median_time_to_reply: null,
            first_contact_reply_at: 1781524800,
            first_assignment_at: null,
            first_admin_reply_at: null,
            first_close_at: null,
            last_assignment_at: null,
            last_contact_reply_at: 1781528440,
            last_admin_reply_at: null,
            last_close_at: null,
            count_reopens: 0,
            count_assignments: 0,
            count_conversation_parts: 1,
          },
          conversation_parts: {
            type: "conversation_part.list",
            conversation_parts: [
              {
                type: "conversation_part",
                id: "403982298",
                part_type: "comment",
                body: "<p>Just to add, it fails right after I click Authorize.</p>",
                created_at: 1781528440,
                updated_at: 1781528440,
                notified_at: 1781528440,
                assigned_to: null,
                author: {
                  type: "user",
                  id: "6620fa1e8f2b3c4d5e6f7890",
                  name: "Priya Desai",
                  email: "priya@northwind.example",
                },
                attachments: [],
                external_id: null,
                redacted: false,
              },
            ],
            total_count: 1,
          },
        },
      },
    },
    docsUrl: "https://developers.intercom.com/docs/references/webhooks/webhook-models",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "intercom",
    providerLabel: "Intercom",
    eventType: "conversation.admin.replied",
    name: "Admin replied to a conversation",
    description: "A teammate answered from the Intercom inbox.",
    body: {
      type: "notification_event",
      topic: "conversation.admin.replied",
      id: "notif_1c9e7b53-2d6a-49f0-8e5c-3a7d9f1b6c04",
      app_id: "a86dr8yl",
      created_at: 1781529100,
      delivery_attempts: 1,
      first_sent_at: 1781529100,
      data: {
        item: {
          type: "conversation",
          id: "195208945002873",
          created_at: 1781524800,
          updated_at: 1781529100,
          waiting_since: null,
          snoozed_until: null,
          source: {
            type: "conversation",
            id: "403982210",
            delivered_as: "customer_initiated",
            subject: "",
            body: "<p>Hi, I'm having trouble connecting my Slack workspace to notifications.</p>",
            author: {
              type: "user",
              id: "6620fa1e8f2b3c4d5e6f7890",
              name: "Priya Desai",
              email: "priya@northwind.example",
            },
            attachments: [],
            url: null,
            redacted: false,
          },
          contacts: {
            type: "contact.list",
            contacts: [{ type: "contact", id: "6620fa1e8f2b3c4d5e6f7890" }],
          },
          teammates: { type: "admin.list", admins: [{ id: "814860", type: "admin" }] },
          admin_assignee_id: 814860,
          team_assignee_id: "5017691",
          open: true,
          state: "open",
          read: true,
          tags: { type: "tag.list", tags: [] },
          priority: "not_priority",
          conversation_rating: null,
          statistics: {
            time_to_assignment: 300,
            time_to_admin_reply: 4300,
            time_to_first_close: null,
            time_to_last_close: null,
            median_time_to_reply: 4300,
            first_contact_reply_at: 1781524800,
            first_assignment_at: 1781525100,
            first_admin_reply_at: 1781529100,
            first_close_at: null,
            last_assignment_at: 1781525100,
            last_contact_reply_at: 1781528440,
            last_admin_reply_at: 1781529100,
            last_close_at: null,
            count_reopens: 0,
            count_assignments: 1,
            count_conversation_parts: 2,
          },
          conversation_parts: {
            type: "conversation_part.list",
            conversation_parts: [
              {
                type: "conversation_part",
                id: "403982355",
                part_type: "comment",
                body: "<p>Thanks for the extra detail, can you confirm which browser you're using?</p>",
                created_at: 1781529100,
                updated_at: 1781529100,
                notified_at: 1781529100,
                assigned_to: null,
                author: {
                  type: "admin",
                  id: "814860",
                  name: "Jordan Mills",
                  email: "jordan@acme.example",
                },
                attachments: [],
                external_id: null,
                redacted: false,
              },
            ],
            total_count: 2,
          },
        },
      },
    },
    docsUrl: "https://developers.intercom.com/docs/references/webhooks/webhook-models",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "intercom",
    providerLabel: "Intercom",
    eventType: "contact.created",
    name: "Contact created",
    description: "A new contact was created in the workspace.",
    body: {
      type: "notification_event",
      topic: "contact.created",
      id: "notif_a3d81f6e-9c02-4b7a-b1e4-5f8d0c2a6b93",
      app_id: "a86dr8yl",
      created_at: 1781524800,
      delivery_attempts: 1,
      first_sent_at: 1781524800,
      data: {
        item: {
          type: "contact",
          id: "6620fa1e8f2b3c4d5e6f7890",
          workspace_id: "a86dr8yl",
          external_id: "cust_48213",
          role: "user",
          email: "priya@northwind.example",
          email_domain: "northwind.example",
          phone: null,
          name: "Priya Desai",
          avatar: null,
          owner_id: null,
          social_profiles: { type: "list", data: [] },
          has_hard_bounced: false,
          marked_email_as_spam: false,
          unsubscribed_from_emails: false,
          created_at: 1781524800,
          updated_at: 1781524800,
          signed_up_at: 1781524800,
          last_seen_at: 1781524800,
          last_replied_at: null,
          last_contacted_at: null,
          last_email_opened_at: null,
          last_email_clicked_at: null,
          language_override: null,
          browser: "chrome",
          browser_version: "126.0.0.0",
          browser_language: "en",
          os: "Mac OS X",
          location: {
            type: "location",
            country: "United States",
            region: "California",
            city: "San Francisco",
          },
          custom_attributes: {},
          tags: {
            type: "list",
            data: [],
            url: "/contacts/6620fa1e8f2b3c4d5e6f7890/tags",
            total_count: 0,
            has_more: false,
          },
          companies: {
            type: "list",
            data: [],
            url: "/contacts/6620fa1e8f2b3c4d5e6f7890/companies",
            total_count: 0,
            has_more: false,
          },
        },
      },
    },
    docsUrl: "https://developers.intercom.com/docs/references/webhooks/webhook-models",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "intercom",
    providerLabel: "Intercom",
    eventType: "contact.deleted",
    name: "Contact deleted",
    description: "A contact was permanently deleted from the workspace.",
    body: {
      type: "notification_event",
      topic: "contact.deleted",
      id: "notif_6e2b4d81-7a5f-4c3e-9d0a-1f6b8c2e4a70",
      app_id: "a86dr8yl",
      created_at: 1781612900,
      delivery_attempts: 1,
      first_sent_at: 1781612900,
      data: {
        item: {
          type: "contact",
          id: "5ba682d23d7cf92bef87bfd4",
          external_id: "cust_10248",
          deleted: true,
        },
      },
    },
    docsUrl: "https://developers.intercom.com/docs/references/webhooks/webhook-models",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
