import { type SampleRecord } from "../sampleRecord.js";

/**
 * Jira Cloud samples. Jira signs webhooks with an `X-Hub-Signature` header (no `-256`), formatted as
 * `sha256=<hex>` HMAC over the raw body - this does not match our `github` preset (which requires the
 * `x-hub-signature-256` header name), so these ship without a `presetId`.
 */
export const samples: SampleRecord[] = [
  {
    provider: "jira",
    providerLabel: "Jira",
    eventType: "jira:issue_created",
    name: "Issue created",
    description: "A new issue was created in a Jira Cloud project.",
    body: {
      timestamp: 1784065200000,
      webhookEvent: "jira:issue_created",
      issue_event_type_name: "issue_created",
      user: {
        self: "https://example.atlassian.net/rest/api/2/user?accountId=5f8a1b2c3d4e5f0a1b2c3d4e",
        accountId: "5f8a1b2c3d4e5f0a1b2c3d4e",
        accountType: "atlassian",
        displayName: "Jordan Lee",
        active: true,
        timeZone: "America/New_York",
      },
      issue: {
        id: "10142",
        self: "https://example.atlassian.net/rest/api/2/issue/10142",
        key: "ENG-482",
        fields: {
          summary: "Webhook retries silently drop after 3 attempts",
          created: "2026-07-13T09:20:00.000-0400",
          issuetype: { id: "10001", name: "Bug" },
          status: { id: "10000", name: "To Do" },
          priority: { id: "3", name: "Medium" },
          project: { id: "10005", key: "ENG", name: "Engineering" },
          labels: ["webhooks", "reliability"],
          assignee: null,
          reporter: {
            accountId: "5f8a1b2c3d4e5f0a1b2c3d4e",
            displayName: "Jordan Lee",
          },
        },
      },
    },
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "jira",
    providerLabel: "Jira",
    eventType: "jira:issue_updated",
    name: "Issue updated",
    description: "An issue's status and priority changed; `changelog.items` lists the field diffs.",
    body: {
      timestamp: 1784068800000,
      webhookEvent: "jira:issue_updated",
      issue_event_type_name: "issue_generic",
      user: {
        self: "https://example.atlassian.net/rest/api/2/user?accountId=6a9b2c3d4e5f6a1b2c3d4e5f",
        accountId: "6a9b2c3d4e5f6a1b2c3d4e5f",
        accountType: "atlassian",
        displayName: "Priya Nair",
        active: true,
        timeZone: "Europe/London",
      },
      issue: {
        id: "10142",
        self: "https://example.atlassian.net/rest/api/2/issue/10142",
        key: "ENG-482",
        fields: {
          summary: "Webhook retries silently drop after 3 attempts",
          created: "2026-07-13T09:20:00.000-0400",
          issuetype: { id: "10001", name: "Bug" },
          status: { id: "10001", name: "In Progress" },
          priority: { id: "2", name: "High" },
          project: { id: "10005", key: "ENG", name: "Engineering" },
          assignee: {
            accountId: "6a9b2c3d4e5f6a1b2c3d4e5f",
            displayName: "Priya Nair",
          },
        },
      },
      changelog: {
        id: "10391",
        items: [
          {
            field: "status",
            fieldtype: "jira",
            from: "10000",
            fromString: "To Do",
            to: "10001",
            toString: "In Progress",
          },
          {
            field: "priority",
            fieldtype: "jira",
            from: "3",
            fromString: "Medium",
            to: "2",
            toString: "High",
          },
        ],
      },
    },
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "jira",
    providerLabel: "Jira",
    eventType: "jira:issue_deleted",
    name: "Issue deleted",
    description: "An issue was permanently deleted from a Jira Cloud project.",
    body: {
      timestamp: 1784072400000,
      webhookEvent: "jira:issue_deleted",
      issue_event_type_name: "issue_deleted",
      user: {
        self: "https://example.atlassian.net/rest/api/2/user?accountId=6a9b2c3d4e5f6a1b2c3d4e5f",
        accountId: "6a9b2c3d4e5f6a1b2c3d4e5f",
        accountType: "atlassian",
        displayName: "Priya Nair",
        active: true,
        timeZone: "Europe/London",
      },
      issue: {
        id: "10098",
        self: "https://example.atlassian.net/rest/api/2/issue/10098",
        key: "ENG-417",
        fields: {
          summary: "Duplicate of ENG-482",
          issuetype: { id: "10001", name: "Bug" },
          status: { id: "10002", name: "Done" },
          project: { id: "10005", key: "ENG", name: "Engineering" },
        },
      },
    },
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "jira",
    providerLabel: "Jira",
    eventType: "comment_created",
    name: "Comment created",
    description: "A comment was added to an issue.",
    body: {
      timestamp: 1784076000000,
      webhookEvent: "comment_created",
      issue_event_type_name: "comment_created",
      user: {
        self: "https://example.atlassian.net/rest/api/2/user?accountId=7b0c3d4e5f6a1b2c3d4e5f6a",
        accountId: "7b0c3d4e5f6a1b2c3d4e5f6a",
        accountType: "atlassian",
        displayName: "Sam Okafor",
        active: true,
        timeZone: "Africa/Lagos",
      },
      issue: {
        id: "10142",
        self: "https://example.atlassian.net/rest/api/2/issue/10142",
        key: "ENG-482",
        fields: {
          summary: "Webhook retries silently drop after 3 attempts",
          issuetype: { id: "10001", name: "Bug" },
          status: { id: "10001", name: "In Progress" },
          project: { id: "10005", key: "ENG", name: "Engineering" },
        },
      },
      comment: {
        self: "https://example.atlassian.net/rest/api/3/issue/ENG-482/comment/48213",
        id: "48213",
        author: {
          accountId: "7b0c3d4e5f6a1b2c3d4e5f6a",
          displayName: "Sam Okafor",
        },
        body: "I can reproduce this - the retry counter resets on redeploy, not per delivery.",
        created: "2026-07-13T11:20:00.000-0400",
        updated: "2026-07-13T11:20:00.000-0400",
      },
    },
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "jira",
    providerLabel: "Jira",
    eventType: "comment_updated",
    name: "Comment updated",
    description: "An existing comment was edited; `updateAuthor` and `updated` reflect the edit.",
    body: {
      timestamp: 1784079600000,
      webhookEvent: "comment_updated",
      issue_event_type_name: "comment_updated",
      user: {
        self: "https://example.atlassian.net/rest/api/2/user?accountId=7b0c3d4e5f6a1b2c3d4e5f6a",
        accountId: "7b0c3d4e5f6a1b2c3d4e5f6a",
        accountType: "atlassian",
        displayName: "Sam Okafor",
        active: true,
        timeZone: "Africa/Lagos",
      },
      issue: {
        id: "10142",
        self: "https://example.atlassian.net/rest/api/2/issue/10142",
        key: "ENG-482",
        fields: {
          summary: "Webhook retries silently drop after 3 attempts",
          issuetype: { id: "10001", name: "Bug" },
          status: { id: "10001", name: "In Progress" },
          project: { id: "10005", key: "ENG", name: "Engineering" },
        },
      },
      comment: {
        self: "https://example.atlassian.net/rest/api/3/issue/ENG-482/comment/48213",
        id: "48213",
        author: {
          accountId: "7b0c3d4e5f6a1b2c3d4e5f6a",
          displayName: "Sam Okafor",
        },
        updateAuthor: {
          accountId: "7b0c3d4e5f6a1b2c3d4e5f6a",
          displayName: "Sam Okafor",
        },
        body: "I can reproduce this - the retry counter resets on redeploy, not per delivery. Filed as ENG-483.",
        created: "2026-07-13T11:20:00.000-0400",
        updated: "2026-07-13T12:05:00.000-0400",
      },
    },
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
