import { type SampleRecord } from "../sampleRecord.js";

/**
 * PagerDuty v3 webhook samples. Every delivery wraps a single `event` envelope
 * (`id`, `event_type`, `resource_type`, `occurred_at`, `agent`, `client`, `data`); `data` is the full
 * incident object at the moment of the event. `eventType` here matches `event.event_type`, the real
 * discriminant. No `presetId` is set (PagerDuty's `X-PagerDuty-Signature: v1=<hex>` is a bespoke
 * HMAC-SHA256 over the raw body with no matching preset).
 */
export const samples: SampleRecord[] = [
  {
    provider: "pagerduty",
    providerLabel: "PagerDuty",
    eventType: "incident.triggered",
    name: "Incident triggered",
    description: "A monitoring integration opened a new incident via the Events API.",
    body: {
      event: {
        id: "01J2Y3ZK9M4Q7R8T2VBN5X0F1A",
        event_type: "incident.triggered",
        resource_type: "incident",
        occurred_at: "2026-07-14T02:11:03Z",
        agent: null,
        client: null,
        data: {
          id: "PT4KHXT",
          type: "incident",
          self: "https://api.pagerduty.com/incidents/PT4KHXT",
          html_url: "https://acme-corp.pagerduty.com/incidents/PT4KHXT",
          number: 4821,
          status: "triggered",
          incident_key: "prod-api-5xx-spike",
          created_at: "2026-07-14T02:11:03Z",
          title: "Elevated 5xx error rate on prod-api-gateway",
          service: {
            id: "PSVCACME1",
            type: "service_reference",
            summary: "prod-api-gateway",
            self: "https://api.pagerduty.com/services/PSVCACME1",
            html_url: "https://acme-corp.pagerduty.com/services/PSVCACME1",
          },
          assignees: [
            {
              id: "PUSRJDOE1",
              type: "user_reference",
              summary: "Jamie Chen",
              self: "https://api.pagerduty.com/users/PUSRJDOE1",
              html_url: "https://acme-corp.pagerduty.com/users/PUSRJDOE1",
            },
          ],
          escalation_policy: {
            id: "PEPACME01",
            type: "escalation_policy_reference",
            summary: "Platform On-Call",
            self: "https://api.pagerduty.com/escalation_policies/PEPACME01",
            html_url: "https://acme-corp.pagerduty.com/escalation_policies/PEPACME01",
          },
          teams: [],
          priority: {
            id: "PRIP1XXX",
            type: "priority_reference",
            summary: "P2",
            self: "https://api.pagerduty.com/priorities/PRIP1XXX",
            html_url: "https://acme-corp.pagerduty.com/account/incident_priorities",
          },
          urgency: "high",
          conference_bridge: null,
          resolve_reason: null,
        },
      },
    },
    docsUrl: "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "pagerduty",
    providerLabel: "PagerDuty",
    eventType: "incident.acknowledged",
    name: "Incident acknowledged",
    description: "The on-call responder acknowledged the incident.",
    body: {
      event: {
        id: "01J2Y40D3H6K8N1P5WCM7Y2G3B",
        event_type: "incident.acknowledged",
        resource_type: "incident",
        occurred_at: "2026-07-14T02:13:47Z",
        agent: {
          id: "PUSRJDOE1",
          type: "user_reference",
          summary: "Jamie Chen",
          self: "https://api.pagerduty.com/users/PUSRJDOE1",
          html_url: "https://acme-corp.pagerduty.com/users/PUSRJDOE1",
        },
        client: null,
        data: {
          id: "PT4KHXT",
          type: "incident",
          self: "https://api.pagerduty.com/incidents/PT4KHXT",
          html_url: "https://acme-corp.pagerduty.com/incidents/PT4KHXT",
          number: 4821,
          status: "acknowledged",
          incident_key: "prod-api-5xx-spike",
          created_at: "2026-07-14T02:11:03Z",
          title: "Elevated 5xx error rate on prod-api-gateway",
          service: {
            id: "PSVCACME1",
            type: "service_reference",
            summary: "prod-api-gateway",
            self: "https://api.pagerduty.com/services/PSVCACME1",
            html_url: "https://acme-corp.pagerduty.com/services/PSVCACME1",
          },
          assignees: [
            {
              id: "PUSRJDOE1",
              type: "user_reference",
              summary: "Jamie Chen",
              self: "https://api.pagerduty.com/users/PUSRJDOE1",
              html_url: "https://acme-corp.pagerduty.com/users/PUSRJDOE1",
            },
          ],
          acknowledgements: [
            {
              at: "2026-07-14T02:13:47Z",
              acknowledger: {
                id: "PUSRJDOE1",
                type: "user_reference",
                summary: "Jamie Chen",
                self: "https://api.pagerduty.com/users/PUSRJDOE1",
                html_url: "https://acme-corp.pagerduty.com/users/PUSRJDOE1",
              },
            },
          ],
          escalation_policy: {
            id: "PEPACME01",
            type: "escalation_policy_reference",
            summary: "Platform On-Call",
            self: "https://api.pagerduty.com/escalation_policies/PEPACME01",
            html_url: "https://acme-corp.pagerduty.com/escalation_policies/PEPACME01",
          },
          teams: [],
          priority: {
            id: "PRIP1XXX",
            type: "priority_reference",
            summary: "P2",
            self: "https://api.pagerduty.com/priorities/PRIP1XXX",
            html_url: "https://acme-corp.pagerduty.com/account/incident_priorities",
          },
          urgency: "high",
          conference_bridge: null,
          last_status_change_at: "2026-07-14T02:13:47Z",
        },
      },
    },
    docsUrl: "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "pagerduty",
    providerLabel: "PagerDuty",
    eventType: "incident.escalated",
    name: "Incident escalated",
    description: "Acknowledgement timed out and the incident escalated to the next on-call level.",
    body: {
      event: {
        id: "01J2Y41V7Q3W9M2N6XDP8Z4H5C",
        event_type: "incident.escalated",
        resource_type: "incident",
        occurred_at: "2026-07-14T02:23:47Z",
        agent: null,
        client: null,
        data: {
          id: "PT4KHXT",
          type: "incident",
          self: "https://api.pagerduty.com/incidents/PT4KHXT",
          html_url: "https://acme-corp.pagerduty.com/incidents/PT4KHXT",
          number: 4821,
          status: "triggered",
          incident_key: "prod-api-5xx-spike",
          created_at: "2026-07-14T02:11:03Z",
          title: "Elevated 5xx error rate on prod-api-gateway",
          service: {
            id: "PSVCACME1",
            type: "service_reference",
            summary: "prod-api-gateway",
            self: "https://api.pagerduty.com/services/PSVCACME1",
            html_url: "https://acme-corp.pagerduty.com/services/PSVCACME1",
          },
          assignees: [
            {
              id: "PUSRMRYS2",
              type: "user_reference",
              summary: "Morgan Reyes",
              self: "https://api.pagerduty.com/users/PUSRMRYS2",
              html_url: "https://acme-corp.pagerduty.com/users/PUSRMRYS2",
            },
          ],
          escalation_policy: {
            id: "PEPACME01",
            type: "escalation_policy_reference",
            summary: "Platform On-Call",
            self: "https://api.pagerduty.com/escalation_policies/PEPACME01",
            html_url: "https://acme-corp.pagerduty.com/escalation_policies/PEPACME01",
          },
          teams: [],
          priority: {
            id: "PRIP1XXX",
            type: "priority_reference",
            summary: "P2",
            self: "https://api.pagerduty.com/priorities/PRIP1XXX",
            html_url: "https://acme-corp.pagerduty.com/account/incident_priorities",
          },
          urgency: "high",
          conference_bridge: null,
          last_status_change_at: "2026-07-14T02:23:47Z",
        },
      },
    },
    docsUrl: "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "pagerduty",
    providerLabel: "PagerDuty",
    eventType: "incident.reassigned",
    name: "Incident reassigned",
    description: "The first responder reassigned the incident to a teammate.",
    body: {
      event: {
        id: "01J2Y42F5T8V1M3P7YCQ9A6J7D",
        event_type: "incident.reassigned",
        resource_type: "incident",
        occurred_at: "2026-07-14T02:25:10Z",
        agent: {
          id: "PUSRJDOE1",
          type: "user_reference",
          summary: "Jamie Chen",
          self: "https://api.pagerduty.com/users/PUSRJDOE1",
          html_url: "https://acme-corp.pagerduty.com/users/PUSRJDOE1",
        },
        client: null,
        data: {
          id: "PT4KHXT",
          type: "incident",
          self: "https://api.pagerduty.com/incidents/PT4KHXT",
          html_url: "https://acme-corp.pagerduty.com/incidents/PT4KHXT",
          number: 4821,
          status: "triggered",
          incident_key: "prod-api-5xx-spike",
          created_at: "2026-07-14T02:11:03Z",
          title: "Elevated 5xx error rate on prod-api-gateway",
          service: {
            id: "PSVCACME1",
            type: "service_reference",
            summary: "prod-api-gateway",
            self: "https://api.pagerduty.com/services/PSVCACME1",
            html_url: "https://acme-corp.pagerduty.com/services/PSVCACME1",
          },
          assignees: [
            {
              id: "PUSRMRYS2",
              type: "user_reference",
              summary: "Morgan Reyes",
              self: "https://api.pagerduty.com/users/PUSRMRYS2",
              html_url: "https://acme-corp.pagerduty.com/users/PUSRMRYS2",
            },
          ],
          escalation_policy: {
            id: "PEPACME01",
            type: "escalation_policy_reference",
            summary: "Platform On-Call",
            self: "https://api.pagerduty.com/escalation_policies/PEPACME01",
            html_url: "https://acme-corp.pagerduty.com/escalation_policies/PEPACME01",
          },
          teams: [],
          priority: {
            id: "PRIP1XXX",
            type: "priority_reference",
            summary: "P2",
            self: "https://api.pagerduty.com/priorities/PRIP1XXX",
            html_url: "https://acme-corp.pagerduty.com/account/incident_priorities",
          },
          urgency: "high",
          conference_bridge: null,
          last_status_change_at: "2026-07-14T02:25:10Z",
        },
      },
    },
    docsUrl: "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "pagerduty",
    providerLabel: "PagerDuty",
    eventType: "incident.resolved",
    name: "Incident resolved",
    description: "The responder resolved the incident after rolling back the bad deploy.",
    body: {
      event: {
        id: "01J2Y43R9W2Y4N6Q8ZDS1B7K9E",
        event_type: "incident.resolved",
        resource_type: "incident",
        occurred_at: "2026-07-14T02:41:52Z",
        agent: {
          id: "PUSRMRYS2",
          type: "user_reference",
          summary: "Morgan Reyes",
          self: "https://api.pagerduty.com/users/PUSRMRYS2",
          html_url: "https://acme-corp.pagerduty.com/users/PUSRMRYS2",
        },
        client: null,
        data: {
          id: "PT4KHXT",
          type: "incident",
          self: "https://api.pagerduty.com/incidents/PT4KHXT",
          html_url: "https://acme-corp.pagerduty.com/incidents/PT4KHXT",
          number: 4821,
          status: "resolved",
          incident_key: "prod-api-5xx-spike",
          created_at: "2026-07-14T02:11:03Z",
          title: "Elevated 5xx error rate on prod-api-gateway",
          service: {
            id: "PSVCACME1",
            type: "service_reference",
            summary: "prod-api-gateway",
            self: "https://api.pagerduty.com/services/PSVCACME1",
            html_url: "https://acme-corp.pagerduty.com/services/PSVCACME1",
          },
          assignees: [],
          escalation_policy: {
            id: "PEPACME01",
            type: "escalation_policy_reference",
            summary: "Platform On-Call",
            self: "https://api.pagerduty.com/escalation_policies/PEPACME01",
            html_url: "https://acme-corp.pagerduty.com/escalation_policies/PEPACME01",
          },
          teams: [],
          priority: {
            id: "PRIP1XXX",
            type: "priority_reference",
            summary: "P2",
            self: "https://api.pagerduty.com/priorities/PRIP1XXX",
            html_url: "https://acme-corp.pagerduty.com/account/incident_priorities",
          },
          urgency: "high",
          conference_bridge: null,
          resolve_reason: null,
          resolved_at: "2026-07-14T02:41:52Z",
          last_status_change_at: "2026-07-14T02:41:52Z",
        },
      },
    },
    docsUrl: "https://developer.pagerduty.com/docs/webhooks/webhook-signatures/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
