import { type SampleRecord } from "../sampleRecord.js";

/**
 * Replicate samples. Replicate signs webhooks with a Standard Webhooks compatible scheme (`webhook-id`
 * / `webhook-timestamp` / `webhook-signature` headers, HMAC-SHA256 over `{id}.{timestamp}.{rawBody}`,
 * `whsec_`-prefixed secret), so `presetId: "svix"` keeps them under the round-trip guarantee. The body
 * is the prediction object itself; there is no separate event envelope, so `eventType` is read from the
 * prediction's own `status` field.
 */
export const samples: SampleRecord[] = [
  {
    provider: "replicate",
    providerLabel: "Replicate",
    presetId: "svix",
    eventType: "starting",
    name: "Prediction starting",
    description: "A prediction has been created and queued but has not started running yet.",
    body: {
      id: "qz7mfxlkw3vdpygt1o8hbnsuae",
      model: "black-forest-labs/flux-schnell",
      version: "a3f1c9d2b7e4809f61a2d5c8e0b3f7a41d6c9b2e5f80a3d17c4b9e2f6a0d3c85",
      input: {
        prompt: "a studio photo of a golden retriever wearing sunglasses",
        num_outputs: 1,
        aspect_ratio: "1:1",
        output_format: "webp",
      },
      logs: null,
      output: null,
      error: null,
      status: "starting",
      created_at: "2026-07-14T09:12:03.221000Z",
      source: "api",
      data_removed: false,
      started_at: null,
      completed_at: null,
      metrics: {},
      urls: {
        web: "https://replicate.com/p/qz7mfxlkw3vdpygt1o8hbnsuae",
        get: "https://api.replicate.com/v1/predictions/qz7mfxlkw3vdpygt1o8hbnsuae",
        cancel: "https://api.replicate.com/v1/predictions/qz7mfxlkw3vdpygt1o8hbnsuae/cancel",
      },
    },
    docsUrl: "https://replicate.com/docs/topics/webhooks/receive-webhook",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "replicate",
    providerLabel: "Replicate",
    presetId: "svix",
    eventType: "processing",
    name: "Prediction processing",
    description: "The model has started running; intermediate logs are streaming in.",
    body: {
      id: "n5tqorvfy28mzbklwdshxc1gpu",
      model: "black-forest-labs/flux-schnell",
      version: "a3f1c9d2b7e4809f61a2d5c8e0b3f7a41d6c9b2e5f80a3d17c4b9e2f6a0d3c85",
      input: {
        prompt: "a watercolor painting of a lighthouse at sunset",
        num_outputs: 1,
        aspect_ratio: "16:9",
        output_format: "webp",
      },
      logs: "Using seed: 48219\nGenerating image...\n",
      output: null,
      error: null,
      status: "processing",
      created_at: "2026-07-14T09:13:41.009000Z",
      source: "api",
      data_removed: false,
      started_at: "2026-07-14T09:13:42.552000Z",
      completed_at: null,
      metrics: {},
      urls: {
        web: "https://replicate.com/p/n5tqorvfy28mzbklwdshxc1gpu",
        get: "https://api.replicate.com/v1/predictions/n5tqorvfy28mzbklwdshxc1gpu",
        cancel: "https://api.replicate.com/v1/predictions/n5tqorvfy28mzbklwdshxc1gpu/cancel",
      },
    },
    docsUrl: "https://replicate.com/docs/topics/webhooks/receive-webhook",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "replicate",
    providerLabel: "Replicate",
    presetId: "svix",
    eventType: "succeeded",
    name: "Prediction succeeded",
    description: "The prediction finished and produced output.",
    body: {
      id: "x9blkfqm37ydrpwnztgohsuic",
      model: "black-forest-labs/flux-schnell",
      version: "a3f1c9d2b7e4809f61a2d5c8e0b3f7a41d6c9b2e5f80a3d17c4b9e2f6a0d3c85",
      input: {
        prompt: "a studio photo of a golden retriever wearing sunglasses",
        num_outputs: 1,
        aspect_ratio: "1:1",
        output_format: "webp",
      },
      logs: "Using seed: 17734\nGenerating image...\nDone in 0.94s\n",
      output: ["https://replicate.delivery/pbxt/QuAty1fakeExampleHash000/out-0.webp"],
      error: null,
      status: "succeeded",
      created_at: "2026-07-14T09:14:55.114000Z",
      source: "api",
      data_removed: false,
      started_at: "2026-07-14T09:14:55.930000Z",
      completed_at: "2026-07-14T09:14:56.871000Z",
      metrics: { predict_time: 0.941263 },
      urls: {
        web: "https://replicate.com/p/x9blkfqm37ydrpwnztgohsuic",
        get: "https://api.replicate.com/v1/predictions/x9blkfqm37ydrpwnztgohsuic",
        cancel: "https://api.replicate.com/v1/predictions/x9blkfqm37ydrpwnztgohsuic/cancel",
      },
    },
    docsUrl: "https://replicate.com/docs/topics/webhooks/receive-webhook",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "replicate",
    providerLabel: "Replicate",
    presetId: "svix",
    eventType: "failed",
    name: "Prediction failed",
    description: "The model raised an error while running and the prediction did not complete.",
    body: {
      id: "f3wgzqmnyt8blkdrpxhcvos19u",
      model: "black-forest-labs/flux-schnell",
      version: "a3f1c9d2b7e4809f61a2d5c8e0b3f7a41d6c9b2e5f80a3d17c4b9e2f6a0d3c85",
      input: {
        prompt: "an ultra high resolution 8k panorama of a mountain range",
        num_outputs: 4,
        aspect_ratio: "21:9",
        output_format: "webp",
      },
      logs: "Using seed: 90271\nGenerating image...\n",
      output: null,
      error: "CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 39.39 GiB total capacity)",
      status: "failed",
      created_at: "2026-07-14T09:16:02.447000Z",
      source: "api",
      data_removed: false,
      started_at: "2026-07-14T09:16:03.018000Z",
      completed_at: "2026-07-14T09:16:07.335000Z",
      metrics: { predict_time: 4.317092 },
      urls: {
        web: "https://replicate.com/p/f3wgzqmnyt8blkdrpxhcvos19u",
        get: "https://api.replicate.com/v1/predictions/f3wgzqmnyt8blkdrpxhcvos19u",
        cancel: "https://api.replicate.com/v1/predictions/f3wgzqmnyt8blkdrpxhcvos19u/cancel",
      },
    },
    docsUrl: "https://replicate.com/docs/topics/webhooks/receive-webhook",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "replicate",
    providerLabel: "Replicate",
    presetId: "svix",
    eventType: "canceled",
    name: "Prediction canceled",
    description: "The prediction was canceled via the cancel endpoint before it finished running.",
    body: {
      id: "h7ldyxqmnzt3fgbkwrpc850osu",
      model: "black-forest-labs/flux-schnell",
      version: "a3f1c9d2b7e4809f61a2d5c8e0b3f7a41d6c9b2e5f80a3d17c4b9e2f6a0d3c85",
      input: {
        prompt: "a neon-lit cyberpunk street market at night",
        num_outputs: 1,
        aspect_ratio: "3:2",
        output_format: "webp",
      },
      logs: "Using seed: 55810\nGenerating image...\n",
      output: null,
      error: null,
      status: "canceled",
      created_at: "2026-07-14T09:17:20.663000Z",
      source: "api",
      data_removed: false,
      started_at: "2026-07-14T09:17:21.204000Z",
      completed_at: "2026-07-14T09:17:23.489000Z",
      metrics: {},
      urls: {
        web: "https://replicate.com/p/h7ldyxqmnzt3fgbkwrpc850osu",
        get: "https://api.replicate.com/v1/predictions/h7ldyxqmnzt3fgbkwrpc850osu",
        cancel: "https://api.replicate.com/v1/predictions/h7ldyxqmnzt3fgbkwrpc850osu/cancel",
      },
    },
    docsUrl: "https://replicate.com/docs/topics/webhooks/receive-webhook",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
