import { type SampleRecord } from "../sampleRecord.js";

/**
 * Slack Events API samples. Slack wraps every event in an `event_callback` envelope and nests the
 * actual event under `event`, so `eventType` here mirrors `event.type`, not the outer `type`. Note
 * that channel-scoped subscriptions like `message.channels` still carry `event.type === "message"`
 * on the wire, so there is no separate "message.channels" sample.
 */
export const samples: SampleRecord[] = [
  {
    provider: "slack",
    providerLabel: "Slack",
    eventType: "app_mention",
    name: "App mentioned",
    description: "The bot was @-mentioned in a channel.",
    body: {
      token: "Jhj5dZrVaK7ZwHHjRyZWjbDl",
      team_id: "T024BE7LD",
      api_app_id: "A0MDYCDME",
      event: {
        type: "app_mention",
        user: "U061F7AUR",
        text: "<@U0LAN0Z89> can you deploy the app?",
        ts: "1515449522.000016",
        channel: "C0T2GACDT",
        event_ts: "1515449522000016",
      },
      type: "event_callback",
      authorizations: [
        {
          team_id: "T024BE7LD",
          user_id: "U0LAN0Z89",
          is_bot: true,
          is_enterprise_install: false,
        },
      ],
      event_id: "Ev0MDYA7HL",
      event_time: 1515449522,
    },
    docsUrl: "https://docs.slack.dev/reference/events/app_mention/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "slack",
    providerLabel: "Slack",
    eventType: "message",
    name: "Message posted in a channel",
    description: "A plain message was posted to a public channel the bot is a member of.",
    body: {
      token: "Jhj5dZrVaK7ZwHHjRyZWjbDl",
      team_id: "T024BE7LD",
      api_app_id: "A0MDYCDME",
      event: {
        type: "message",
        user: "U061F7AUR",
        text: "Deploy finished, all green.",
        ts: "1355517523.000005",
        channel: "C0T2GACDT",
        channel_type: "channel",
        event_ts: "1355517523.000005",
      },
      type: "event_callback",
      authorizations: [
        {
          team_id: "T024BE7LD",
          user_id: "U0LAN0Z89",
          is_bot: true,
          is_enterprise_install: false,
        },
      ],
      event_id: "Ev0MDYA7HM",
      event_time: 1355517523,
    },
    docsUrl: "https://docs.slack.dev/reference/events/message/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "slack",
    providerLabel: "Slack",
    eventType: "reaction_added",
    name: "Reaction added",
    description: "A user added an emoji reaction to a message.",
    body: {
      token: "Jhj5dZrVaK7ZwHHjRyZWjbDl",
      team_id: "T024BE7LD",
      api_app_id: "A0MDYCDME",
      event: {
        type: "reaction_added",
        user: "U061F7AUR",
        reaction: "thumbsup",
        item_user: "U0LAN0Z89",
        item: {
          type: "message",
          channel: "C0T2GACDT",
          ts: "1360782400.498405",
          channel_type: "channel",
        },
        event_ts: "1360782804.083113",
      },
      type: "event_callback",
      authorizations: [
        {
          team_id: "T024BE7LD",
          user_id: "U0LAN0Z89",
          is_bot: true,
          is_enterprise_install: false,
        },
      ],
      event_id: "Ev0MDYA7HN",
      event_time: 1360782804,
    },
    docsUrl: "https://docs.slack.dev/reference/events/reaction_added/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "slack",
    providerLabel: "Slack",
    eventType: "member_joined_channel",
    name: "Member joined channel",
    description: "A user joined a channel the bot is watching.",
    body: {
      token: "Jhj5dZrVaK7ZwHHjRyZWjbDl",
      team_id: "T024BE7LD",
      api_app_id: "A0MDYCDME",
      event: {
        type: "member_joined_channel",
        user: "W061F7AUR",
        channel: "C0T2GACDT",
        channel_type: "C",
        team: "T024BE7LD",
        inviter: "U0LAN0Z89",
      },
      type: "event_callback",
      authorizations: [
        {
          team_id: "T024BE7LD",
          user_id: "U0LAN0Z89",
          is_bot: true,
          is_enterprise_install: false,
        },
      ],
      event_id: "Ev0MDYA7HP",
      event_time: 1515500000,
    },
    docsUrl: "https://docs.slack.dev/reference/events/member_joined_channel/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "slack",
    providerLabel: "Slack",
    eventType: "app_home_opened",
    name: "App home opened",
    description: "A user opened the bot's Home tab in the Slack app.",
    body: {
      token: "Jhj5dZrVaK7ZwHHjRyZWjbDl",
      team_id: "T024BE7LD",
      api_app_id: "A0MDYCDME",
      event: {
        type: "app_home_opened",
        user: "U061F7AUR",
        channel: "D0T2GACDT",
        event_ts: "1515449522000016",
        tab: "home",
        view: {
          id: "V0MDYA7HQ",
          team_id: "T024BE7LD",
          type: "home",
          blocks: [],
          private_metadata: "",
          callback_id: "",
          hash: "1231232323.12321312",
          clear_on_close: false,
          notify_on_close: false,
          root_view_id: "V0MDYA7HQ",
          app_id: "A0MDYCDME",
          external_id: "",
          app_installed_team_id: "T024BE7LD",
          bot_id: "B0MDYCDMF",
        },
      },
      type: "event_callback",
      authorizations: [
        {
          team_id: "T024BE7LD",
          user_id: "U0LAN0Z89",
          is_bot: true,
          is_enterprise_install: false,
        },
      ],
      event_id: "Ev0MDYA7HQ",
      event_time: 1515449522,
    },
    docsUrl: "https://docs.slack.dev/reference/events/app_home_opened/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
