import { type SampleRecord } from "../sampleRecord.js";

/**
 * Twilio samples. Requests are `application/x-www-form-urlencoded`, decoded here as a flat string
 * key/value object (Twilio's own wire format has no nesting and every value is a string, including
 * numeric-looking ones like `NumMedia`/`CallDuration`). No `presetId`: Twilio's `X-Twilio-Signature`
 * scheme (HMAC-SHA1 over the webhook URL + sorted params, base64) does not match any of our verifier
 * presets. Covers the two products that hit a Twilio webhook URL: inbound Messaging (SMS/MMS) and Voice
 * (the initial call request plus status-callback requests).
 */
export const samples: SampleRecord[] = [
  {
    provider: "twilio",
    providerLabel: "Twilio",
    eventType: "message.inbound",
    name: "Inbound SMS",
    description:
      "A text message received by a Twilio number. `Body` is the message text; `SmsStatus` is always `received` for inbound messages.",
    body: {
      ToCountry: "US",
      ToState: "CA",
      SmsMessageSid: "SMe1e2b7c8f5a34d6d8b8c1a2b3c4d5e60",
      NumMedia: "0",
      ToCity: "SAN FRANCISCO",
      FromZip: "94107",
      FromState: "CA",
      SmsStatus: "received",
      FromCity: "SAN FRANCISCO",
      Body: "Running about 10 min late, on my way!",
      FromCountry: "US",
      To: "+14155550142",
      MessagingServiceSid: "MG9f8e7d6c5b4a3928f1e0d9c8b7a6f5e4",
      ToZip: "94107",
      NumSegments: "1",
      MessageSid: "SMe1e2b7c8f5a34d6d8b8c1a2b3c4d5e60",
      AccountSid: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      SmsSid: "SMe1e2b7c8f5a34d6d8b8c1a2b3c4d5e60",
      From: "+14155550198",
      ApiVersion: "2010-04-01",
    },
    docsUrl: "https://www.twilio.com/docs/messaging/guides/webhook-request",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "twilio",
    providerLabel: "Twilio",
    eventType: "message.inbound-mms",
    name: "Inbound MMS",
    description:
      "A picture message received by a Twilio number. `NumMedia` is non-zero and each attachment is described by an indexed `MediaUrl{N}`/`MediaContentType{N}` pair.",
    body: {
      ToCountry: "US",
      ToState: "CA",
      SmsMessageSid: "MM2b3c4d5e6f7890a1b2c3d4e5f6071829",
      NumMedia: "1",
      ToCity: "SAN FRANCISCO",
      FromZip: "94107",
      FromState: "CA",
      SmsStatus: "received",
      FromCity: "SAN FRANCISCO",
      Body: "Here's the receipt",
      FromCountry: "US",
      To: "+14155550142",
      MessagingServiceSid: "MG9f8e7d6c5b4a3928f1e0d9c8b7a6f5e4",
      ToZip: "94107",
      NumSegments: "1",
      MessageSid: "MM2b3c4d5e6f7890a1b2c3d4e5f6071829",
      AccountSid: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      SmsSid: "MM2b3c4d5e6f7890a1b2c3d4e5f6071829",
      From: "+14155550198",
      ApiVersion: "2010-04-01",
      MediaContentType0: "image/jpeg",
      MediaUrl0:
        "https://api.twilio.com/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Messages/MM2b3c4d5e6f7890a1b2c3d4e5f6071829/Media/ME3c4d5e6f7890a1b2c3d4e5f60718293",
    },
    docsUrl: "https://www.twilio.com/docs/messaging/guides/webhook-request",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "twilio",
    providerLabel: "Twilio",
    eventType: "call.inbound",
    name: "Incoming call",
    description:
      "Twilio's request to the voice webhook URL when a call comes in. `CallStatus` is `ringing`; the app answers with TwiML in the response.",
    body: {
      CallSid: "CA3f9e8d7c6b5a4938271605f4e3d2c1b0a",
      AccountSid: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      From: "+14155550198",
      To: "+14155550142",
      CallStatus: "ringing",
      ApiVersion: "2010-04-01",
      Direction: "inbound",
      FromCity: "SAN FRANCISCO",
      FromState: "CA",
      FromZip: "94107",
      FromCountry: "US",
      ToCity: "SAN FRANCISCO",
      ToState: "CA",
      ToZip: "94107",
      ToCountry: "US",
    },
    docsUrl: "https://www.twilio.com/docs/voice/twiml#twilios-request-to-your-application",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "twilio",
    providerLabel: "Twilio",
    eventType: "call.status-callback",
    name: "Call status callback: completed",
    description:
      "A voice `StatusCallback` request after the call ended normally. `CallDuration` (seconds) is only present once `CallStatus` reaches a terminal value.",
    body: {
      CallSid: "CA3f9e8d7c6b5a4938271605f4e3d2c1b0a",
      AccountSid: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      From: "+14155550198",
      To: "+14155550142",
      CallStatus: "completed",
      ApiVersion: "2010-04-01",
      Direction: "inbound",
      CallDuration: "187",
      Timestamp: "Wed, 15 Jul 2026 14:32:18 +0000",
      CallbackSource: "call-progress-events",
      SequenceNumber: "3",
      SipResponseCode: "200",
    },
    docsUrl: "https://www.twilio.com/docs/usage/webhooks/voice-webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "twilio",
    providerLabel: "Twilio",
    eventType: "call.status-callback",
    name: "Call status callback: no-answer",
    description:
      "A voice `StatusCallback` request for an outbound call nobody picked up. No `CallDuration` is sent for non-`completed` terminal statuses.",
    body: {
      CallSid: "CA7c6b5a4938271605f4e3d2c1b0a9f8e7d",
      AccountSid: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      From: "+14155550142",
      To: "+14155550287",
      CallStatus: "no-answer",
      ApiVersion: "2010-04-01",
      Direction: "outbound-api",
      Timestamp: "Wed, 15 Jul 2026 09:04:52 +0000",
      CallbackSource: "call-progress-events",
      SequenceNumber: "2",
    },
    docsUrl: "https://www.twilio.com/docs/usage/webhooks/voice-webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
