import { type SampleRecord } from "../sampleRecord.js";

/**
 * Vercel account/integration webhook samples. Every event shares the envelope
 * `{ id, type, createdAt, region, payload }`; `type` is the discriminant. Vercel signs with a bespoke
 * `x-vercel-signature` HMAC-SHA1-over-raw-body scheme (no preset match), so no `presetId` is set on
 * any sample here. `payload.deployment.meta` is documented only as an opaque metadata map; the values
 * below model the common git-integration keys Vercel populates for a GitHub-linked project.
 */
export const samples: SampleRecord[] = [
  {
    provider: "vercel",
    providerLabel: "Vercel",
    eventType: "deployment.created",
    name: "Deployment created",
    description: "A new deployment was initiated, e.g. from a git push or `vercel deploy`.",
    body: {
      id: "5FQ3bE5aQhZ1Vv2c4vXYzP1LhqoT",
      type: "deployment.created",
      createdAt: 1752520920123,
      region: null,
      payload: {
        team: { id: "team_LLHUOMOoDlqOp8wPE4kFo9pE" },
        user: { id: "K4amb7K9dhQC1c3Vg6M4VZur" },
        alias: ["storefront.vercel.app", "storefront-git-main-acme.vercel.app"],
        deployment: {
          id: "dpl_5m3gYqz6JhKGLnvGGqSpVsXQ2vHz",
          meta: {
            githubCommitAuthorLogin: "priyanair",
            githubCommitMessage: "fix: correct cart subtotal rounding",
            githubCommitOrg: "acme",
            githubCommitRef: "main",
            githubCommitRepo: "storefront",
            githubCommitRepoId: "612345678",
            githubCommitSha: "8f3a1c2e9b4d7f6a2c8e1b5d9a3f7c2e6b8d4a1f",
            githubDeployment: "1",
            githubOrg: "acme",
            githubRepo: "storefront",
            githubRepoOwnerType: "organization",
          },
          url: "storefront-git-main-acme.vercel.app",
          name: "storefront",
        },
        links: {
          deployment: "https://vercel.com/acme/storefront/5m3gYqz6JhKGLnvGGqSpVsXQ2vHz",
          project: "https://vercel.com/acme/storefront",
        },
        target: "production",
        project: { id: "prj_8Xc1kQnR3vTz9YbW2fA6mLhE" },
        plan: "pro",
        regions: ["iad1"],
      },
    },
    docsUrl: "https://vercel.com/docs/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "vercel",
    providerLabel: "Vercel",
    eventType: "deployment.succeeded",
    name: "Deployment succeeded",
    description: "A deployment finished building and all blocking checks passed.",
    body: {
      id: "9Kd2wR7fXmQ3Vv8c5bYpZ4LhqrN",
      type: "deployment.succeeded",
      createdAt: 1752520998456,
      region: null,
      payload: {
        team: { id: "team_LLHUOMOoDlqOp8wPE4kFo9pE" },
        user: { id: "K4amb7K9dhQC1c3Vg6M4VZur" },
        deployment: {
          id: "dpl_5m3gYqz6JhKGLnvGGqSpVsXQ2vHz",
          meta: {
            githubCommitAuthorLogin: "priyanair",
            githubCommitMessage: "fix: correct cart subtotal rounding",
            githubCommitOrg: "acme",
            githubCommitRef: "main",
            githubCommitRepo: "storefront",
            githubCommitRepoId: "612345678",
            githubCommitSha: "8f3a1c2e9b4d7f6a2c8e1b5d9a3f7c2e6b8d4a1f",
            githubDeployment: "1",
            githubOrg: "acme",
            githubRepo: "storefront",
            githubRepoOwnerType: "organization",
          },
          url: "storefront-git-main-acme.vercel.app",
          name: "storefront",
        },
        links: {
          deployment: "https://vercel.com/acme/storefront/5m3gYqz6JhKGLnvGGqSpVsXQ2vHz",
          project: "https://vercel.com/acme/storefront",
        },
        target: "production",
        project: { id: "prj_8Xc1kQnR3vTz9YbW2fA6mLhE" },
        plan: "pro",
        regions: ["iad1"],
      },
    },
    docsUrl: "https://vercel.com/docs/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "vercel",
    providerLabel: "Vercel",
    eventType: "deployment.error",
    name: "Deployment error",
    description: "A deployment failed to build.",
    body: {
      id: "2Hn8pL4dWkR6Tz1c9vXmA3JhqsE",
      type: "deployment.error",
      createdAt: 1752521045789,
      region: null,
      payload: {
        team: { id: "team_LLHUOMOoDlqOp8wPE4kFo9pE" },
        user: { id: "6b1e9d3a4c7f4b2e8a9d1c6f3b8e" },
        deployment: {
          id: "dpl_7qXn2vBpKzGjWm4cRfLtYs9AeHd6",
          meta: {
            githubCommitAuthorLogin: "marcuswebb",
            githubCommitMessage: "feat: add checkout address autocomplete",
            githubCommitOrg: "acme",
            githubCommitRef: "feature/checkout-autocomplete",
            githubCommitRepo: "storefront",
            githubCommitRepoId: "612345678",
            githubCommitSha: "3c7e9b1a5d8f2c6e4a9b7d3f1c8e5a2b6d9f4c1e",
            githubDeployment: "1",
            githubOrg: "acme",
            githubRepo: "storefront",
            githubRepoOwnerType: "organization",
          },
          url: "storefront-git-checkout-autocomplete-acme.vercel.app",
          name: "storefront",
        },
        links: {
          deployment: "https://vercel.com/acme/storefront/7qXn2vBpKzGjWm4cRfLtYs9AeHd6",
          project: "https://vercel.com/acme/storefront",
        },
        target: null,
        project: { id: "prj_8Xc1kQnR3vTz9YbW2fA6mLhE" },
        plan: "pro",
        regions: ["iad1"],
      },
    },
    docsUrl: "https://vercel.com/docs/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "vercel",
    providerLabel: "Vercel",
    eventType: "deployment.canceled",
    name: "Deployment canceled",
    description: "A deployment was canceled, e.g. superseded by a newer push to the same branch.",
    body: {
      id: "4Mp6rT9fYnQ2Vx3c7bZoW5LhqtF",
      type: "deployment.canceled",
      createdAt: 1752521102345,
      region: null,
      payload: {
        team: { id: "team_LLHUOMOoDlqOp8wPE4kFo9pE" },
        user: { id: "6b1e9d3a4c7f4b2e8a9d1c6f3b8e" },
        deployment: {
          id: "dpl_1bYw6qGkPzRjNm8cVfEtLs4AeXd9",
          meta: {
            githubCommitAuthorLogin: "marcuswebb",
            githubCommitMessage: "feat: add checkout address autocomplete (v2)",
            githubCommitOrg: "acme",
            githubCommitRef: "feature/checkout-autocomplete",
            githubCommitRepo: "storefront",
            githubCommitRepoId: "612345678",
            githubCommitSha: "9a4f2c8e6b1d3a7f5c9e2b8d4a6f1c3e7b9d5a2f",
            githubDeployment: "1",
            githubOrg: "acme",
            githubRepo: "storefront",
            githubRepoOwnerType: "organization",
          },
          url: "storefront-git-checkout-autocomplete-acme.vercel.app",
          name: "storefront",
        },
        links: {
          deployment: "https://vercel.com/acme/storefront/1bYw6qGkPzRjNm8cVfEtLs4AeXd9",
          project: "https://vercel.com/acme/storefront",
        },
        target: null,
        project: { id: "prj_8Xc1kQnR3vTz9YbW2fA6mLhE" },
        plan: "pro",
        regions: ["iad1"],
      },
    },
    docsUrl: "https://vercel.com/docs/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
