import { type SampleRecord } from "../sampleRecord.js";

/**
 * WorkOS samples. WorkOS signs webhooks with its own `WorkOS-Signature: t=,v1=` scheme (HMAC-SHA256
 * over `{t}.{rawBody}`), which does not match our `stripe` preset's header name, so these ship without
 * a `presetId`. Every event shares the envelope `{ id, event, data, created_at, context }`.
 */
export const samples: SampleRecord[] = [
  {
    provider: "workos",
    providerLabel: "WorkOS",
    eventType: "dsync.user.created",
    name: "Directory user created",
    description: "A new user appeared in a connected Directory Sync (SCIM) provider.",
    body: {
      id: "event_01J4QF7R2N8T6R3P0M5NDS8WYA",
      event: "dsync.user.created",
      data: {
        object: "directory_user",
        id: "directory_user_01J4QF6VN8T6R3P0M5NDS8WYB",
        directory_id: "directory_01J4QF5PM7S5R2P9M4NDS6WVC",
        organization_id: "org_01J4QF4ZK6R4Q1P8M3NDS5WUD",
        idp_id: "2839573",
        email: "priya.nair@example.com",
        first_name: "Priya",
        last_name: "Nair",
        emails: [{ type: "work", value: "priya.nair@example.com", primary: true }],
        job_title: "Staff Engineer",
        username: "priya.nair",
        state: "active",
        custom_attributes: { department: "Engineering" },
        raw_attributes: {
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:User"],
          userName: "priya.nair",
          active: true,
        },
        role: { slug: "member" },
        roles: [{ slug: "member" }],
        created_at: "2026-07-13T09:20:00.000Z",
        updated_at: "2026-07-13T09:20:00.000Z",
      },
      created_at: "2026-07-13T09:20:01.104Z",
      context: { client_id: "client_01J4QF3XH5Q3P0M9NDS4WTYE" },
    },
    docsUrl: "https://workos.com/docs/events/data-syncing/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "workos",
    providerLabel: "WorkOS",
    eventType: "dsync.group.created",
    name: "Directory group created",
    description: "A new group appeared in a connected Directory Sync provider.",
    body: {
      id: "event_01J4QFB9P9U7S4Q1N6PDT9XZF",
      event: "dsync.group.created",
      data: {
        object: "directory_group",
        id: "directory_group_01J4QFA3Q0V8T5R2P7PDT0YAG",
        idp_id: "9284756",
        directory_id: "directory_01J4QF5PM7S5R2P9M4NDS6WVC",
        organization_id: "org_01J4QF4ZK6R4Q1P8M3NDS5WUD",
        name: "Engineering",
        raw_attributes: {
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:Group"],
          displayName: "Engineering",
        },
        created_at: "2026-07-13T09:21:15.000Z",
        updated_at: "2026-07-13T09:21:15.000Z",
      },
      created_at: "2026-07-13T09:21:15.892Z",
      context: { client_id: "client_01J4QF3XH5Q3P0M9NDS4WTYE" },
    },
    docsUrl: "https://workos.com/docs/events/data-syncing/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "workos",
    providerLabel: "WorkOS",
    eventType: "connection.activated",
    name: "SSO connection activated",
    description: "An SSO connection finished setup and is now able to authenticate users.",
    body: {
      id: "event_01J4QFD2R1W9T6S3P8QEU1ZBH",
      event: "connection.activated",
      data: {
        object: "connection",
        id: "conn_01J4QFC5S2X0U7T4Q9QEU2ACJ",
        organization_id: "org_01J4QF4ZK6R4Q1P8M3NDS5WUD",
        connection_type: "OktaSAML",
        name: "Acme Corp Okta",
        state: "active",
        domains: [
          {
            object: "connection_domain",
            id: "conn_domain_01J4QFBWT3Y1V8U5R0RFV3BDK",
            domain: "acmecorp.com",
          },
        ],
        created_at: "2026-07-10T16:04:22.000Z",
        updated_at: "2026-07-13T09:22:40.000Z",
      },
      created_at: "2026-07-13T09:22:40.331Z",
      context: { client_id: "client_01J4QF3XH5Q3P0M9NDS4WTYE" },
    },
    docsUrl: "https://workos.com/docs/events/data-syncing/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "workos",
    providerLabel: "WorkOS",
    eventType: "user.created",
    name: "User created",
    description: "A new AuthKit / User Management user signed up or was invited.",
    body: {
      id: "event_01J4QFF6T4Z2V9U6S1RFV4CEM",
      event: "user.created",
      data: {
        object: "user",
        id: "user_01J4QFE9U5A3W0V7T2SGW5DFN",
        email: "jordan.lee@example.com",
        email_verified: false,
        first_name: "Jordan",
        last_name: "Lee",
        profile_picture_url: null,
        external_id: null,
        metadata: {},
        last_sign_in_at: null,
        created_at: "2026-07-13T09:23:55.000Z",
        updated_at: "2026-07-13T09:23:55.000Z",
      },
      created_at: "2026-07-13T09:23:55.410Z",
      context: { client_id: "client_01J4QF3XH5Q3P0M9NDS4WTYE" },
    },
    docsUrl: "https://workos.com/docs/events/data-syncing/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "workos",
    providerLabel: "WorkOS",
    eventType: "user.deleted",
    name: "User deleted",
    description: "A User Management user was permanently deleted.",
    body: {
      id: "event_01J4QFH8V6B4X1W8U3THX6DGP",
      event: "user.deleted",
      data: {
        object: "user",
        id: "user_01J4QFG1W7C5Y2X9V4THX7EHQ",
        email: "sam.okafor@example.com",
        email_verified: true,
        first_name: "Sam",
        last_name: "Okafor",
        profile_picture_url: null,
        external_id: null,
        metadata: {},
        last_sign_in_at: "2026-07-10T14:02:33.000Z",
        created_at: "2026-05-02T11:10:00.000Z",
        updated_at: "2026-07-13T09:25:03.000Z",
      },
      created_at: "2026-07-13T09:25:03.777Z",
      context: { client_id: "client_01J4QF3XH5Q3P0M9NDS4WTYE" },
    },
    docsUrl: "https://workos.com/docs/events/data-syncing/webhooks",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
