import { type SampleRecord } from "../sampleRecord.js";

/**
 * Zendesk samples. Zendesk webhooks are driven by triggers/automations where an admin authors the JSON
 * body from content placeholders (e.g. `{{ticket.id}}`, `{{ticket.assignee.email}}`), so there is no
 * fixed payload schema across accounts - these model the common flattened "ticket" shape used in
 * Zendesk's own webhook examples. No `presetId`: the signing scheme (base64 HMAC-SHA256 over
 * `timestamp + body`, headers `X-Zendesk-Webhook-Signature` / `X-Zendesk-Webhook-Timestamp`) matches
 * none of our presets.
 */
export const samples: SampleRecord[] = [
  {
    provider: "zendesk",
    providerLabel: "Zendesk",
    eventType: "ticket.created",
    name: "Ticket created",
    description: "A new support ticket was created and is awaiting first response.",
    body: {
      ticket_id: 30482,
      ticket_url: "https://republic-widgets.zendesk.com/agent/tickets/30482",
      subject: "Unable to reset my password",
      description: "I tried the password reset link three times and never received the email.",
      status: "new",
      priority: "normal",
      type: "question",
      tags: ["password", "login"],
      group: "Support Tier 1",
      organization: "Acme Corp",
      requester_name: "Jamie Chen",
      requester_email: "jamie.chen@example.com",
      assignee_name: "",
      assignee_email: "",
      created_at: "2026-07-10T14:02:31Z",
      updated_at: "2026-07-10T14:02:31Z",
    },
    docsUrl: "https://developer.zendesk.com/documentation/webhooks/verifying/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "zendesk",
    providerLabel: "Zendesk",
    eventType: "ticket.updated",
    name: "Ticket assigned",
    description: "The ticket was picked up and assigned to an agent; status moved to open.",
    body: {
      ticket_id: 30482,
      ticket_url: "https://republic-widgets.zendesk.com/agent/tickets/30482",
      subject: "Unable to reset my password",
      description: "I tried the password reset link three times and never received the email.",
      status: "open",
      priority: "normal",
      type: "question",
      tags: ["password", "login"],
      group: "Support Tier 1",
      organization: "Acme Corp",
      requester_name: "Jamie Chen",
      requester_email: "jamie.chen@example.com",
      assignee_name: "Morgan Reyes",
      assignee_email: "morgan.reyes@republic-widgets.example.com",
      created_at: "2026-07-10T14:02:31Z",
      updated_at: "2026-07-10T14:05:47Z",
    },
    docsUrl: "https://developer.zendesk.com/documentation/webhooks/verifying/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "zendesk",
    providerLabel: "Zendesk",
    eventType: "ticket.updated",
    name: "Ticket priority escalated",
    description:
      "Priority was raised to urgent after the requester replied that billing was affected.",
    body: {
      ticket_id: 30510,
      ticket_url: "https://republic-widgets.zendesk.com/agent/tickets/30510",
      subject: "Duplicate charge on last invoice",
      description: "My card was charged twice for the July invoice, please refund the duplicate.",
      status: "open",
      priority: "urgent",
      type: "incident",
      tags: ["billing", "refund"],
      group: "Billing",
      organization: "Acme Corp",
      requester_name: "Dana Okafor",
      requester_email: "dana.okafor@example.com",
      assignee_name: "Priya Nair",
      assignee_email: "priya.nair@republic-widgets.example.com",
      created_at: "2026-07-11T09:15:02Z",
      updated_at: "2026-07-11T09:41:18Z",
    },
    docsUrl: "https://developer.zendesk.com/documentation/webhooks/verifying/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "zendesk",
    providerLabel: "Zendesk",
    eventType: "ticket.updated",
    name: "Public reply added",
    description: "An agent posted a public comment; `latest_comment` carries the reply text.",
    body: {
      ticket_id: 30510,
      ticket_url: "https://republic-widgets.zendesk.com/agent/tickets/30510",
      subject: "Duplicate charge on last invoice",
      status: "pending",
      priority: "urgent",
      type: "incident",
      requester_name: "Dana Okafor",
      requester_email: "dana.okafor@example.com",
      assignee_name: "Priya Nair",
      assignee_email: "priya.nair@republic-widgets.example.com",
      latest_comment:
        "Thanks for flagging this - I've refunded the duplicate charge, you should see it in 3-5 business days.",
      latest_comment_is_public: true,
      created_at: "2026-07-11T09:15:02Z",
      updated_at: "2026-07-11T10:02:55Z",
    },
    docsUrl: "https://developer.zendesk.com/documentation/webhooks/verifying/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
  {
    provider: "zendesk",
    providerLabel: "Zendesk",
    eventType: "ticket.updated",
    name: "Ticket solved",
    description: "The ticket reached a terminal state after the requester confirmed the fix.",
    body: {
      ticket_id: 30482,
      ticket_url: "https://republic-widgets.zendesk.com/agent/tickets/30482",
      subject: "Unable to reset my password",
      status: "solved",
      priority: "normal",
      type: "question",
      tags: ["password", "login"],
      group: "Support Tier 1",
      organization: "Acme Corp",
      requester_name: "Jamie Chen",
      requester_email: "jamie.chen@example.com",
      assignee_name: "Morgan Reyes",
      assignee_email: "morgan.reyes@republic-widgets.example.com",
      created_at: "2026-07-10T14:02:31Z",
      updated_at: "2026-07-10T15:30:09Z",
    },
    docsUrl: "https://developer.zendesk.com/documentation/webhooks/verifying/",
    provenance: { kind: "handauthored", snapshotDate: "2026-07" },
  },
];
